package com.template.base.domain.criteria;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

// WARNING - @mbg.generated
// This file is automatically generated by MyBatis Generator, do not modify.
public class PermissionCriteria extends BaseCriteria {
    private static final Set<String> COLUMNS;

    static {
        COLUMNS = new HashSet<>();
        COLUMNS.add("id");
        COLUMNS.add("name");
        COLUMNS.add("pid");
        COLUMNS.add("descpt");
        COLUMNS.add("url");
        COLUMNS.add("create_time");
        COLUMNS.add("update_time");
        COLUMNS.add("del_flag");
    }

    public PermissionCriteria ascOrderBy(String  ... fields) {
        addOrderBy("asc", fields);
        return this;
    }

    public PermissionCriteria descOrderBy(String  ... fields) {
        addOrderBy("desc", fields);
        return this;
    }

    public PermissionCriteria or() {
        oredCriteria.add(new BracketCriteria());
        return this;
    }

    public PermissionCriteria setLimit(Long limit) {
        this.limit = limit;
        return this;
    }

    public PermissionCriteria setOffset(Long offset) {
        this.offset = offset;
        return this;
    }

    public PermissionCriteria setForUpdate(boolean forUpdate) {
        this.forUpdate = forUpdate;
        return this;
    }

    @Override
    protected boolean hasColumn(String column) {
        return COLUMNS.contains(column);
    }

    public PermissionCriteria andIdIsNull() {
        lastCriteria().addCriterion("id is null");
        return this;
    }

    public PermissionCriteria andIdIsNotNull() {
        lastCriteria().addCriterion("id is not null");
        return this;
    }

    public PermissionCriteria andIdEqualTo(Integer value) {
        lastCriteria().addCriterion("id =", value, "id");
        return this;
    }

    public PermissionCriteria andIdNotEqualTo(Integer value) {
        lastCriteria().addCriterion("id <>", value, "id");
        return this;
    }

    public PermissionCriteria andIdGreaterThan(Integer value) {
        lastCriteria().addCriterion("id >", value, "id");
        return this;
    }

    public PermissionCriteria andIdGreaterThanOrEqualTo(Integer value) {
        lastCriteria().addCriterion("id >=", value, "id");
        return this;
    }

    public PermissionCriteria andIdLessThan(Integer value) {
        lastCriteria().addCriterion("id <", value, "id");
        return this;
    }

    public PermissionCriteria andIdLessThanOrEqualTo(Integer value) {
        lastCriteria().addCriterion("id <=", value, "id");
        return this;
    }

    public PermissionCriteria andIdIn(List<Integer> values) {
        lastCriteria().addCriterion("id in", values, "id");
        return this;
    }

    public PermissionCriteria andIdNotIn(List<Integer> values) {
        lastCriteria().addCriterion("id not in", values, "id");
        return this;
    }

    public PermissionCriteria andIdBetween(Integer value1, Integer value2) {
        lastCriteria().addCriterion("id between", value1, value2, "id");
        return this;
    }

    public PermissionCriteria andIdNotBetween(Integer value1, Integer value2) {
        lastCriteria().addCriterion("id not between", value1, value2, "id");
        return this;
    }

    public PermissionCriteria andNameIsNull() {
        lastCriteria().addCriterion("name is null");
        return this;
    }

    public PermissionCriteria andNameIsNotNull() {
        lastCriteria().addCriterion("name is not null");
        return this;
    }

    public PermissionCriteria andNameEqualTo(String value) {
        lastCriteria().addCriterion("name =", value, "name");
        return this;
    }

    public PermissionCriteria andNameNotEqualTo(String value) {
        lastCriteria().addCriterion("name <>", value, "name");
        return this;
    }

    public PermissionCriteria andNameGreaterThan(String value) {
        lastCriteria().addCriterion("name >", value, "name");
        return this;
    }

    public PermissionCriteria andNameGreaterThanOrEqualTo(String value) {
        lastCriteria().addCriterion("name >=", value, "name");
        return this;
    }

    public PermissionCriteria andNameLessThan(String value) {
        lastCriteria().addCriterion("name <", value, "name");
        return this;
    }

    public PermissionCriteria andNameLessThanOrEqualTo(String value) {
        lastCriteria().addCriterion("name <=", value, "name");
        return this;
    }

    public PermissionCriteria andNameLike(String value) {
        lastCriteria().addCriterion("name like", value, "name");
        return this;
    }

    public PermissionCriteria andNameNotLike(String value) {
        lastCriteria().addCriterion("name not like", value, "name");
        return this;
    }

    public PermissionCriteria andNameIn(List<String> values) {
        lastCriteria().addCriterion("name in", values, "name");
        return this;
    }

    public PermissionCriteria andNameNotIn(List<String> values) {
        lastCriteria().addCriterion("name not in", values, "name");
        return this;
    }

    public PermissionCriteria andNameBetween(String value1, String value2) {
        lastCriteria().addCriterion("name between", value1, value2, "name");
        return this;
    }

    public PermissionCriteria andNameNotBetween(String value1, String value2) {
        lastCriteria().addCriterion("name not between", value1, value2, "name");
        return this;
    }

    public PermissionCriteria andPidIsNull() {
        lastCriteria().addCriterion("pid is null");
        return this;
    }

    public PermissionCriteria andPidIsNotNull() {
        lastCriteria().addCriterion("pid is not null");
        return this;
    }

    public PermissionCriteria andPidEqualTo(Integer value) {
        lastCriteria().addCriterion("pid =", value, "pid");
        return this;
    }

    public PermissionCriteria andPidNotEqualTo(Integer value) {
        lastCriteria().addCriterion("pid <>", value, "pid");
        return this;
    }

    public PermissionCriteria andPidGreaterThan(Integer value) {
        lastCriteria().addCriterion("pid >", value, "pid");
        return this;
    }

    public PermissionCriteria andPidGreaterThanOrEqualTo(Integer value) {
        lastCriteria().addCriterion("pid >=", value, "pid");
        return this;
    }

    public PermissionCriteria andPidLessThan(Integer value) {
        lastCriteria().addCriterion("pid <", value, "pid");
        return this;
    }

    public PermissionCriteria andPidLessThanOrEqualTo(Integer value) {
        lastCriteria().addCriterion("pid <=", value, "pid");
        return this;
    }

    public PermissionCriteria andPidIn(List<Integer> values) {
        lastCriteria().addCriterion("pid in", values, "pid");
        return this;
    }

    public PermissionCriteria andPidNotIn(List<Integer> values) {
        lastCriteria().addCriterion("pid not in", values, "pid");
        return this;
    }

    public PermissionCriteria andPidBetween(Integer value1, Integer value2) {
        lastCriteria().addCriterion("pid between", value1, value2, "pid");
        return this;
    }

    public PermissionCriteria andPidNotBetween(Integer value1, Integer value2) {
        lastCriteria().addCriterion("pid not between", value1, value2, "pid");
        return this;
    }

    public PermissionCriteria andDescptIsNull() {
        lastCriteria().addCriterion("descpt is null");
        return this;
    }

    public PermissionCriteria andDescptIsNotNull() {
        lastCriteria().addCriterion("descpt is not null");
        return this;
    }

    public PermissionCriteria andDescptEqualTo(String value) {
        lastCriteria().addCriterion("descpt =", value, "descpt");
        return this;
    }

    public PermissionCriteria andDescptNotEqualTo(String value) {
        lastCriteria().addCriterion("descpt <>", value, "descpt");
        return this;
    }

    public PermissionCriteria andDescptGreaterThan(String value) {
        lastCriteria().addCriterion("descpt >", value, "descpt");
        return this;
    }

    public PermissionCriteria andDescptGreaterThanOrEqualTo(String value) {
        lastCriteria().addCriterion("descpt >=", value, "descpt");
        return this;
    }

    public PermissionCriteria andDescptLessThan(String value) {
        lastCriteria().addCriterion("descpt <", value, "descpt");
        return this;
    }

    public PermissionCriteria andDescptLessThanOrEqualTo(String value) {
        lastCriteria().addCriterion("descpt <=", value, "descpt");
        return this;
    }

    public PermissionCriteria andDescptLike(String value) {
        lastCriteria().addCriterion("descpt like", value, "descpt");
        return this;
    }

    public PermissionCriteria andDescptNotLike(String value) {
        lastCriteria().addCriterion("descpt not like", value, "descpt");
        return this;
    }

    public PermissionCriteria andDescptIn(List<String> values) {
        lastCriteria().addCriterion("descpt in", values, "descpt");
        return this;
    }

    public PermissionCriteria andDescptNotIn(List<String> values) {
        lastCriteria().addCriterion("descpt not in", values, "descpt");
        return this;
    }

    public PermissionCriteria andDescptBetween(String value1, String value2) {
        lastCriteria().addCriterion("descpt between", value1, value2, "descpt");
        return this;
    }

    public PermissionCriteria andDescptNotBetween(String value1, String value2) {
        lastCriteria().addCriterion("descpt not between", value1, value2, "descpt");
        return this;
    }

    public PermissionCriteria andUrlIsNull() {
        lastCriteria().addCriterion("url is null");
        return this;
    }

    public PermissionCriteria andUrlIsNotNull() {
        lastCriteria().addCriterion("url is not null");
        return this;
    }

    public PermissionCriteria andUrlEqualTo(String value) {
        lastCriteria().addCriterion("url =", value, "url");
        return this;
    }

    public PermissionCriteria andUrlNotEqualTo(String value) {
        lastCriteria().addCriterion("url <>", value, "url");
        return this;
    }

    public PermissionCriteria andUrlGreaterThan(String value) {
        lastCriteria().addCriterion("url >", value, "url");
        return this;
    }

    public PermissionCriteria andUrlGreaterThanOrEqualTo(String value) {
        lastCriteria().addCriterion("url >=", value, "url");
        return this;
    }

    public PermissionCriteria andUrlLessThan(String value) {
        lastCriteria().addCriterion("url <", value, "url");
        return this;
    }

    public PermissionCriteria andUrlLessThanOrEqualTo(String value) {
        lastCriteria().addCriterion("url <=", value, "url");
        return this;
    }

    public PermissionCriteria andUrlLike(String value) {
        lastCriteria().addCriterion("url like", value, "url");
        return this;
    }

    public PermissionCriteria andUrlNotLike(String value) {
        lastCriteria().addCriterion("url not like", value, "url");
        return this;
    }

    public PermissionCriteria andUrlIn(List<String> values) {
        lastCriteria().addCriterion("url in", values, "url");
        return this;
    }

    public PermissionCriteria andUrlNotIn(List<String> values) {
        lastCriteria().addCriterion("url not in", values, "url");
        return this;
    }

    public PermissionCriteria andUrlBetween(String value1, String value2) {
        lastCriteria().addCriterion("url between", value1, value2, "url");
        return this;
    }

    public PermissionCriteria andUrlNotBetween(String value1, String value2) {
        lastCriteria().addCriterion("url not between", value1, value2, "url");
        return this;
    }

    public PermissionCriteria andCreateTimeIsNull() {
        lastCriteria().addCriterion("create_time is null");
        return this;
    }

    public PermissionCriteria andCreateTimeIsNotNull() {
        lastCriteria().addCriterion("create_time is not null");
        return this;
    }

    public PermissionCriteria andCreateTimeEqualTo(String value) {
        lastCriteria().addCriterion("create_time =", value, "createTime");
        return this;
    }

    public PermissionCriteria andCreateTimeNotEqualTo(String value) {
        lastCriteria().addCriterion("create_time <>", value, "createTime");
        return this;
    }

    public PermissionCriteria andCreateTimeGreaterThan(String value) {
        lastCriteria().addCriterion("create_time >", value, "createTime");
        return this;
    }

    public PermissionCriteria andCreateTimeGreaterThanOrEqualTo(String value) {
        lastCriteria().addCriterion("create_time >=", value, "createTime");
        return this;
    }

    public PermissionCriteria andCreateTimeLessThan(String value) {
        lastCriteria().addCriterion("create_time <", value, "createTime");
        return this;
    }

    public PermissionCriteria andCreateTimeLessThanOrEqualTo(String value) {
        lastCriteria().addCriterion("create_time <=", value, "createTime");
        return this;
    }

    public PermissionCriteria andCreateTimeLike(String value) {
        lastCriteria().addCriterion("create_time like", value, "createTime");
        return this;
    }

    public PermissionCriteria andCreateTimeNotLike(String value) {
        lastCriteria().addCriterion("create_time not like", value, "createTime");
        return this;
    }

    public PermissionCriteria andCreateTimeIn(List<String> values) {
        lastCriteria().addCriterion("create_time in", values, "createTime");
        return this;
    }

    public PermissionCriteria andCreateTimeNotIn(List<String> values) {
        lastCriteria().addCriterion("create_time not in", values, "createTime");
        return this;
    }

    public PermissionCriteria andCreateTimeBetween(String value1, String value2) {
        lastCriteria().addCriterion("create_time between", value1, value2, "createTime");
        return this;
    }

    public PermissionCriteria andCreateTimeNotBetween(String value1, String value2) {
        lastCriteria().addCriterion("create_time not between", value1, value2, "createTime");
        return this;
    }

    public PermissionCriteria andUpdateTimeIsNull() {
        lastCriteria().addCriterion("update_time is null");
        return this;
    }

    public PermissionCriteria andUpdateTimeIsNotNull() {
        lastCriteria().addCriterion("update_time is not null");
        return this;
    }

    public PermissionCriteria andUpdateTimeEqualTo(String value) {
        lastCriteria().addCriterion("update_time =", value, "updateTime");
        return this;
    }

    public PermissionCriteria andUpdateTimeNotEqualTo(String value) {
        lastCriteria().addCriterion("update_time <>", value, "updateTime");
        return this;
    }

    public PermissionCriteria andUpdateTimeGreaterThan(String value) {
        lastCriteria().addCriterion("update_time >", value, "updateTime");
        return this;
    }

    public PermissionCriteria andUpdateTimeGreaterThanOrEqualTo(String value) {
        lastCriteria().addCriterion("update_time >=", value, "updateTime");
        return this;
    }

    public PermissionCriteria andUpdateTimeLessThan(String value) {
        lastCriteria().addCriterion("update_time <", value, "updateTime");
        return this;
    }

    public PermissionCriteria andUpdateTimeLessThanOrEqualTo(String value) {
        lastCriteria().addCriterion("update_time <=", value, "updateTime");
        return this;
    }

    public PermissionCriteria andUpdateTimeLike(String value) {
        lastCriteria().addCriterion("update_time like", value, "updateTime");
        return this;
    }

    public PermissionCriteria andUpdateTimeNotLike(String value) {
        lastCriteria().addCriterion("update_time not like", value, "updateTime");
        return this;
    }

    public PermissionCriteria andUpdateTimeIn(List<String> values) {
        lastCriteria().addCriterion("update_time in", values, "updateTime");
        return this;
    }

    public PermissionCriteria andUpdateTimeNotIn(List<String> values) {
        lastCriteria().addCriterion("update_time not in", values, "updateTime");
        return this;
    }

    public PermissionCriteria andUpdateTimeBetween(String value1, String value2) {
        lastCriteria().addCriterion("update_time between", value1, value2, "updateTime");
        return this;
    }

    public PermissionCriteria andUpdateTimeNotBetween(String value1, String value2) {
        lastCriteria().addCriterion("update_time not between", value1, value2, "updateTime");
        return this;
    }

    public PermissionCriteria andDelFlagIsNull() {
        lastCriteria().addCriterion("del_flag is null");
        return this;
    }

    public PermissionCriteria andDelFlagIsNotNull() {
        lastCriteria().addCriterion("del_flag is not null");
        return this;
    }

    public PermissionCriteria andDelFlagEqualTo(Integer value) {
        lastCriteria().addCriterion("del_flag =", value, "delFlag");
        return this;
    }

    public PermissionCriteria andDelFlagNotEqualTo(Integer value) {
        lastCriteria().addCriterion("del_flag <>", value, "delFlag");
        return this;
    }

    public PermissionCriteria andDelFlagGreaterThan(Integer value) {
        lastCriteria().addCriterion("del_flag >", value, "delFlag");
        return this;
    }

    public PermissionCriteria andDelFlagGreaterThanOrEqualTo(Integer value) {
        lastCriteria().addCriterion("del_flag >=", value, "delFlag");
        return this;
    }

    public PermissionCriteria andDelFlagLessThan(Integer value) {
        lastCriteria().addCriterion("del_flag <", value, "delFlag");
        return this;
    }

    public PermissionCriteria andDelFlagLessThanOrEqualTo(Integer value) {
        lastCriteria().addCriterion("del_flag <=", value, "delFlag");
        return this;
    }

    public PermissionCriteria andDelFlagIn(List<Integer> values) {
        lastCriteria().addCriterion("del_flag in", values, "delFlag");
        return this;
    }

    public PermissionCriteria andDelFlagNotIn(List<Integer> values) {
        lastCriteria().addCriterion("del_flag not in", values, "delFlag");
        return this;
    }

    public PermissionCriteria andDelFlagBetween(Integer value1, Integer value2) {
        lastCriteria().addCriterion("del_flag between", value1, value2, "delFlag");
        return this;
    }

    public PermissionCriteria andDelFlagNotBetween(Integer value1, Integer value2) {
        lastCriteria().addCriterion("del_flag not between", value1, value2, "delFlag");
        return this;
    }

    public static PermissionCriteria idIsNull() {
        return new PermissionCriteria().andIdIsNull();
    }

    public static PermissionCriteria idIsNotNull() {
        return new PermissionCriteria().andIdIsNotNull();
    }

    public static PermissionCriteria idEqualTo(Integer value) {
        return new PermissionCriteria().andIdEqualTo(value);
    }

    public static PermissionCriteria idNotEqualTo(Integer value) {
        return new PermissionCriteria().andIdNotEqualTo(value);
    }

    public static PermissionCriteria idGreaterThan(Integer value) {
        return new PermissionCriteria().andIdGreaterThan(value);
    }

    public static PermissionCriteria idGreaterThanOrEqualTo(Integer value) {
        return new PermissionCriteria().andIdGreaterThanOrEqualTo(value);
    }

    public static PermissionCriteria idLessThan(Integer value) {
        return new PermissionCriteria().andIdLessThan(value);
    }

    public static PermissionCriteria idLessThanOrEqualTo(Integer value) {
        return new PermissionCriteria().andIdLessThanOrEqualTo(value);
    }

    public static PermissionCriteria idIn(List<Integer> values) {
        return new PermissionCriteria().andIdIn(values);
    }

    public static PermissionCriteria idNotIn(List<Integer> values) {
        return new PermissionCriteria().andIdNotIn(values);
    }

    public static PermissionCriteria idBetween(Integer value1, Integer value2) {
        return new PermissionCriteria().andIdBetween(value1, value2);
    }

    public static PermissionCriteria idNotBetween(Integer value1, Integer value2) {
        return new PermissionCriteria().andIdNotBetween(value1, value2);
    }

    public static PermissionCriteria nameIsNull() {
        return new PermissionCriteria().andNameIsNull();
    }

    public static PermissionCriteria nameIsNotNull() {
        return new PermissionCriteria().andNameIsNotNull();
    }

    public static PermissionCriteria nameEqualTo(String value) {
        return new PermissionCriteria().andNameEqualTo(value);
    }

    public static PermissionCriteria nameNotEqualTo(String value) {
        return new PermissionCriteria().andNameNotEqualTo(value);
    }

    public static PermissionCriteria nameGreaterThan(String value) {
        return new PermissionCriteria().andNameGreaterThan(value);
    }

    public static PermissionCriteria nameGreaterThanOrEqualTo(String value) {
        return new PermissionCriteria().andNameGreaterThanOrEqualTo(value);
    }

    public static PermissionCriteria nameLessThan(String value) {
        return new PermissionCriteria().andNameLessThan(value);
    }

    public static PermissionCriteria nameLessThanOrEqualTo(String value) {
        return new PermissionCriteria().andNameLessThanOrEqualTo(value);
    }

    public static PermissionCriteria nameLike(String value) {
        return new PermissionCriteria().andNameLike(value);
    }

    public static PermissionCriteria nameNotLike(String value) {
        return new PermissionCriteria().andNameNotLike(value);
    }

    public static PermissionCriteria nameIn(List<String> values) {
        return new PermissionCriteria().andNameIn(values);
    }

    public static PermissionCriteria nameNotIn(List<String> values) {
        return new PermissionCriteria().andNameNotIn(values);
    }

    public static PermissionCriteria nameBetween(String value1, String value2) {
        return new PermissionCriteria().andNameBetween(value1, value2);
    }

    public static PermissionCriteria nameNotBetween(String value1, String value2) {
        return new PermissionCriteria().andNameNotBetween(value1, value2);
    }

    public static PermissionCriteria pidIsNull() {
        return new PermissionCriteria().andPidIsNull();
    }

    public static PermissionCriteria pidIsNotNull() {
        return new PermissionCriteria().andPidIsNotNull();
    }

    public static PermissionCriteria pidEqualTo(Integer value) {
        return new PermissionCriteria().andPidEqualTo(value);
    }

    public static PermissionCriteria pidNotEqualTo(Integer value) {
        return new PermissionCriteria().andPidNotEqualTo(value);
    }

    public static PermissionCriteria pidGreaterThan(Integer value) {
        return new PermissionCriteria().andPidGreaterThan(value);
    }

    public static PermissionCriteria pidGreaterThanOrEqualTo(Integer value) {
        return new PermissionCriteria().andPidGreaterThanOrEqualTo(value);
    }

    public static PermissionCriteria pidLessThan(Integer value) {
        return new PermissionCriteria().andPidLessThan(value);
    }

    public static PermissionCriteria pidLessThanOrEqualTo(Integer value) {
        return new PermissionCriteria().andPidLessThanOrEqualTo(value);
    }

    public static PermissionCriteria pidIn(List<Integer> values) {
        return new PermissionCriteria().andPidIn(values);
    }

    public static PermissionCriteria pidNotIn(List<Integer> values) {
        return new PermissionCriteria().andPidNotIn(values);
    }

    public static PermissionCriteria pidBetween(Integer value1, Integer value2) {
        return new PermissionCriteria().andPidBetween(value1, value2);
    }

    public static PermissionCriteria pidNotBetween(Integer value1, Integer value2) {
        return new PermissionCriteria().andPidNotBetween(value1, value2);
    }

    public static PermissionCriteria descptIsNull() {
        return new PermissionCriteria().andDescptIsNull();
    }

    public static PermissionCriteria descptIsNotNull() {
        return new PermissionCriteria().andDescptIsNotNull();
    }

    public static PermissionCriteria descptEqualTo(String value) {
        return new PermissionCriteria().andDescptEqualTo(value);
    }

    public static PermissionCriteria descptNotEqualTo(String value) {
        return new PermissionCriteria().andDescptNotEqualTo(value);
    }

    public static PermissionCriteria descptGreaterThan(String value) {
        return new PermissionCriteria().andDescptGreaterThan(value);
    }

    public static PermissionCriteria descptGreaterThanOrEqualTo(String value) {
        return new PermissionCriteria().andDescptGreaterThanOrEqualTo(value);
    }

    public static PermissionCriteria descptLessThan(String value) {
        return new PermissionCriteria().andDescptLessThan(value);
    }

    public static PermissionCriteria descptLessThanOrEqualTo(String value) {
        return new PermissionCriteria().andDescptLessThanOrEqualTo(value);
    }

    public static PermissionCriteria descptLike(String value) {
        return new PermissionCriteria().andDescptLike(value);
    }

    public static PermissionCriteria descptNotLike(String value) {
        return new PermissionCriteria().andDescptNotLike(value);
    }

    public static PermissionCriteria descptIn(List<String> values) {
        return new PermissionCriteria().andDescptIn(values);
    }

    public static PermissionCriteria descptNotIn(List<String> values) {
        return new PermissionCriteria().andDescptNotIn(values);
    }

    public static PermissionCriteria descptBetween(String value1, String value2) {
        return new PermissionCriteria().andDescptBetween(value1, value2);
    }

    public static PermissionCriteria descptNotBetween(String value1, String value2) {
        return new PermissionCriteria().andDescptNotBetween(value1, value2);
    }

    public static PermissionCriteria urlIsNull() {
        return new PermissionCriteria().andUrlIsNull();
    }

    public static PermissionCriteria urlIsNotNull() {
        return new PermissionCriteria().andUrlIsNotNull();
    }

    public static PermissionCriteria urlEqualTo(String value) {
        return new PermissionCriteria().andUrlEqualTo(value);
    }

    public static PermissionCriteria urlNotEqualTo(String value) {
        return new PermissionCriteria().andUrlNotEqualTo(value);
    }

    public static PermissionCriteria urlGreaterThan(String value) {
        return new PermissionCriteria().andUrlGreaterThan(value);
    }

    public static PermissionCriteria urlGreaterThanOrEqualTo(String value) {
        return new PermissionCriteria().andUrlGreaterThanOrEqualTo(value);
    }

    public static PermissionCriteria urlLessThan(String value) {
        return new PermissionCriteria().andUrlLessThan(value);
    }

    public static PermissionCriteria urlLessThanOrEqualTo(String value) {
        return new PermissionCriteria().andUrlLessThanOrEqualTo(value);
    }

    public static PermissionCriteria urlLike(String value) {
        return new PermissionCriteria().andUrlLike(value);
    }

    public static PermissionCriteria urlNotLike(String value) {
        return new PermissionCriteria().andUrlNotLike(value);
    }

    public static PermissionCriteria urlIn(List<String> values) {
        return new PermissionCriteria().andUrlIn(values);
    }

    public static PermissionCriteria urlNotIn(List<String> values) {
        return new PermissionCriteria().andUrlNotIn(values);
    }

    public static PermissionCriteria urlBetween(String value1, String value2) {
        return new PermissionCriteria().andUrlBetween(value1, value2);
    }

    public static PermissionCriteria urlNotBetween(String value1, String value2) {
        return new PermissionCriteria().andUrlNotBetween(value1, value2);
    }

    public static PermissionCriteria createTimeIsNull() {
        return new PermissionCriteria().andCreateTimeIsNull();
    }

    public static PermissionCriteria createTimeIsNotNull() {
        return new PermissionCriteria().andCreateTimeIsNotNull();
    }

    public static PermissionCriteria createTimeEqualTo(String value) {
        return new PermissionCriteria().andCreateTimeEqualTo(value);
    }

    public static PermissionCriteria createTimeNotEqualTo(String value) {
        return new PermissionCriteria().andCreateTimeNotEqualTo(value);
    }

    public static PermissionCriteria createTimeGreaterThan(String value) {
        return new PermissionCriteria().andCreateTimeGreaterThan(value);
    }

    public static PermissionCriteria createTimeGreaterThanOrEqualTo(String value) {
        return new PermissionCriteria().andCreateTimeGreaterThanOrEqualTo(value);
    }

    public static PermissionCriteria createTimeLessThan(String value) {
        return new PermissionCriteria().andCreateTimeLessThan(value);
    }

    public static PermissionCriteria createTimeLessThanOrEqualTo(String value) {
        return new PermissionCriteria().andCreateTimeLessThanOrEqualTo(value);
    }

    public static PermissionCriteria createTimeLike(String value) {
        return new PermissionCriteria().andCreateTimeLike(value);
    }

    public static PermissionCriteria createTimeNotLike(String value) {
        return new PermissionCriteria().andCreateTimeNotLike(value);
    }

    public static PermissionCriteria createTimeIn(List<String> values) {
        return new PermissionCriteria().andCreateTimeIn(values);
    }

    public static PermissionCriteria createTimeNotIn(List<String> values) {
        return new PermissionCriteria().andCreateTimeNotIn(values);
    }

    public static PermissionCriteria createTimeBetween(String value1, String value2) {
        return new PermissionCriteria().andCreateTimeBetween(value1, value2);
    }

    public static PermissionCriteria createTimeNotBetween(String value1, String value2) {
        return new PermissionCriteria().andCreateTimeNotBetween(value1, value2);
    }

    public static PermissionCriteria updateTimeIsNull() {
        return new PermissionCriteria().andUpdateTimeIsNull();
    }

    public static PermissionCriteria updateTimeIsNotNull() {
        return new PermissionCriteria().andUpdateTimeIsNotNull();
    }

    public static PermissionCriteria updateTimeEqualTo(String value) {
        return new PermissionCriteria().andUpdateTimeEqualTo(value);
    }

    public static PermissionCriteria updateTimeNotEqualTo(String value) {
        return new PermissionCriteria().andUpdateTimeNotEqualTo(value);
    }

    public static PermissionCriteria updateTimeGreaterThan(String value) {
        return new PermissionCriteria().andUpdateTimeGreaterThan(value);
    }

    public static PermissionCriteria updateTimeGreaterThanOrEqualTo(String value) {
        return new PermissionCriteria().andUpdateTimeGreaterThanOrEqualTo(value);
    }

    public static PermissionCriteria updateTimeLessThan(String value) {
        return new PermissionCriteria().andUpdateTimeLessThan(value);
    }

    public static PermissionCriteria updateTimeLessThanOrEqualTo(String value) {
        return new PermissionCriteria().andUpdateTimeLessThanOrEqualTo(value);
    }

    public static PermissionCriteria updateTimeLike(String value) {
        return new PermissionCriteria().andUpdateTimeLike(value);
    }

    public static PermissionCriteria updateTimeNotLike(String value) {
        return new PermissionCriteria().andUpdateTimeNotLike(value);
    }

    public static PermissionCriteria updateTimeIn(List<String> values) {
        return new PermissionCriteria().andUpdateTimeIn(values);
    }

    public static PermissionCriteria updateTimeNotIn(List<String> values) {
        return new PermissionCriteria().andUpdateTimeNotIn(values);
    }

    public static PermissionCriteria updateTimeBetween(String value1, String value2) {
        return new PermissionCriteria().andUpdateTimeBetween(value1, value2);
    }

    public static PermissionCriteria updateTimeNotBetween(String value1, String value2) {
        return new PermissionCriteria().andUpdateTimeNotBetween(value1, value2);
    }

    public static PermissionCriteria delFlagIsNull() {
        return new PermissionCriteria().andDelFlagIsNull();
    }

    public static PermissionCriteria delFlagIsNotNull() {
        return new PermissionCriteria().andDelFlagIsNotNull();
    }

    public static PermissionCriteria delFlagEqualTo(Integer value) {
        return new PermissionCriteria().andDelFlagEqualTo(value);
    }

    public static PermissionCriteria delFlagNotEqualTo(Integer value) {
        return new PermissionCriteria().andDelFlagNotEqualTo(value);
    }

    public static PermissionCriteria delFlagGreaterThan(Integer value) {
        return new PermissionCriteria().andDelFlagGreaterThan(value);
    }

    public static PermissionCriteria delFlagGreaterThanOrEqualTo(Integer value) {
        return new PermissionCriteria().andDelFlagGreaterThanOrEqualTo(value);
    }

    public static PermissionCriteria delFlagLessThan(Integer value) {
        return new PermissionCriteria().andDelFlagLessThan(value);
    }

    public static PermissionCriteria delFlagLessThanOrEqualTo(Integer value) {
        return new PermissionCriteria().andDelFlagLessThanOrEqualTo(value);
    }

    public static PermissionCriteria delFlagIn(List<Integer> values) {
        return new PermissionCriteria().andDelFlagIn(values);
    }

    public static PermissionCriteria delFlagNotIn(List<Integer> values) {
        return new PermissionCriteria().andDelFlagNotIn(values);
    }

    public static PermissionCriteria delFlagBetween(Integer value1, Integer value2) {
        return new PermissionCriteria().andDelFlagBetween(value1, value2);
    }

    public static PermissionCriteria delFlagNotBetween(Integer value1, Integer value2) {
        return new PermissionCriteria().andDelFlagNotBetween(value1, value2);
    }
}