package com.template.base.domain.criteria;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

// WARNING - @mbg.generated
// This file is automatically generated by MyBatis Generator, do not modify.
public class RoleCriteria extends BaseCriteria {
    private static final Set<String> COLUMNS;

    static {
        COLUMNS = new HashSet<>();
        COLUMNS.add("id");
        COLUMNS.add("role_name");
        COLUMNS.add("role_desc");
        COLUMNS.add("permissions");
        COLUMNS.add("create_time");
        COLUMNS.add("update_time");
        COLUMNS.add("role_status");
    }

    public RoleCriteria ascOrderBy(String  ... fields) {
        addOrderBy("asc", fields);
        return this;
    }

    public RoleCriteria descOrderBy(String  ... fields) {
        addOrderBy("desc", fields);
        return this;
    }

    public RoleCriteria or() {
        oredCriteria.add(new BracketCriteria());
        return this;
    }

    public RoleCriteria setLimit(Long limit) {
        this.limit = limit;
        return this;
    }

    public RoleCriteria setOffset(Long offset) {
        this.offset = offset;
        return this;
    }

    public RoleCriteria setForUpdate(boolean forUpdate) {
        this.forUpdate = forUpdate;
        return this;
    }

    @Override
    protected boolean hasColumn(String column) {
        return COLUMNS.contains(column);
    }

    public RoleCriteria andIdIsNull() {
        lastCriteria().addCriterion("id is null");
        return this;
    }

    public RoleCriteria andIdIsNotNull() {
        lastCriteria().addCriterion("id is not null");
        return this;
    }

    public RoleCriteria andIdEqualTo(Integer value) {
        lastCriteria().addCriterion("id =", value, "id");
        return this;
    }

    public RoleCriteria andIdNotEqualTo(Integer value) {
        lastCriteria().addCriterion("id <>", value, "id");
        return this;
    }

    public RoleCriteria andIdGreaterThan(Integer value) {
        lastCriteria().addCriterion("id >", value, "id");
        return this;
    }

    public RoleCriteria andIdGreaterThanOrEqualTo(Integer value) {
        lastCriteria().addCriterion("id >=", value, "id");
        return this;
    }

    public RoleCriteria andIdLessThan(Integer value) {
        lastCriteria().addCriterion("id <", value, "id");
        return this;
    }

    public RoleCriteria andIdLessThanOrEqualTo(Integer value) {
        lastCriteria().addCriterion("id <=", value, "id");
        return this;
    }

    public RoleCriteria andIdIn(List<Integer> values) {
        lastCriteria().addCriterion("id in", values, "id");
        return this;
    }

    public RoleCriteria andIdNotIn(List<Integer> values) {
        lastCriteria().addCriterion("id not in", values, "id");
        return this;
    }

    public RoleCriteria andIdBetween(Integer value1, Integer value2) {
        lastCriteria().addCriterion("id between", value1, value2, "id");
        return this;
    }

    public RoleCriteria andIdNotBetween(Integer value1, Integer value2) {
        lastCriteria().addCriterion("id not between", value1, value2, "id");
        return this;
    }

    public RoleCriteria andRoleNameIsNull() {
        lastCriteria().addCriterion("role_name is null");
        return this;
    }

    public RoleCriteria andRoleNameIsNotNull() {
        lastCriteria().addCriterion("role_name is not null");
        return this;
    }

    public RoleCriteria andRoleNameEqualTo(String value) {
        lastCriteria().addCriterion("role_name =", value, "roleName");
        return this;
    }

    public RoleCriteria andRoleNameNotEqualTo(String value) {
        lastCriteria().addCriterion("role_name <>", value, "roleName");
        return this;
    }

    public RoleCriteria andRoleNameGreaterThan(String value) {
        lastCriteria().addCriterion("role_name >", value, "roleName");
        return this;
    }

    public RoleCriteria andRoleNameGreaterThanOrEqualTo(String value) {
        lastCriteria().addCriterion("role_name >=", value, "roleName");
        return this;
    }

    public RoleCriteria andRoleNameLessThan(String value) {
        lastCriteria().addCriterion("role_name <", value, "roleName");
        return this;
    }

    public RoleCriteria andRoleNameLessThanOrEqualTo(String value) {
        lastCriteria().addCriterion("role_name <=", value, "roleName");
        return this;
    }

    public RoleCriteria andRoleNameLike(String value) {
        lastCriteria().addCriterion("role_name like", value, "roleName");
        return this;
    }

    public RoleCriteria andRoleNameNotLike(String value) {
        lastCriteria().addCriterion("role_name not like", value, "roleName");
        return this;
    }

    public RoleCriteria andRoleNameIn(List<String> values) {
        lastCriteria().addCriterion("role_name in", values, "roleName");
        return this;
    }

    public RoleCriteria andRoleNameNotIn(List<String> values) {
        lastCriteria().addCriterion("role_name not in", values, "roleName");
        return this;
    }

    public RoleCriteria andRoleNameBetween(String value1, String value2) {
        lastCriteria().addCriterion("role_name between", value1, value2, "roleName");
        return this;
    }

    public RoleCriteria andRoleNameNotBetween(String value1, String value2) {
        lastCriteria().addCriterion("role_name not between", value1, value2, "roleName");
        return this;
    }

    public RoleCriteria andRoleDescIsNull() {
        lastCriteria().addCriterion("role_desc is null");
        return this;
    }

    public RoleCriteria andRoleDescIsNotNull() {
        lastCriteria().addCriterion("role_desc is not null");
        return this;
    }

    public RoleCriteria andRoleDescEqualTo(String value) {
        lastCriteria().addCriterion("role_desc =", value, "roleDesc");
        return this;
    }

    public RoleCriteria andRoleDescNotEqualTo(String value) {
        lastCriteria().addCriterion("role_desc <>", value, "roleDesc");
        return this;
    }

    public RoleCriteria andRoleDescGreaterThan(String value) {
        lastCriteria().addCriterion("role_desc >", value, "roleDesc");
        return this;
    }

    public RoleCriteria andRoleDescGreaterThanOrEqualTo(String value) {
        lastCriteria().addCriterion("role_desc >=", value, "roleDesc");
        return this;
    }

    public RoleCriteria andRoleDescLessThan(String value) {
        lastCriteria().addCriterion("role_desc <", value, "roleDesc");
        return this;
    }

    public RoleCriteria andRoleDescLessThanOrEqualTo(String value) {
        lastCriteria().addCriterion("role_desc <=", value, "roleDesc");
        return this;
    }

    public RoleCriteria andRoleDescLike(String value) {
        lastCriteria().addCriterion("role_desc like", value, "roleDesc");
        return this;
    }

    public RoleCriteria andRoleDescNotLike(String value) {
        lastCriteria().addCriterion("role_desc not like", value, "roleDesc");
        return this;
    }

    public RoleCriteria andRoleDescIn(List<String> values) {
        lastCriteria().addCriterion("role_desc in", values, "roleDesc");
        return this;
    }

    public RoleCriteria andRoleDescNotIn(List<String> values) {
        lastCriteria().addCriterion("role_desc not in", values, "roleDesc");
        return this;
    }

    public RoleCriteria andRoleDescBetween(String value1, String value2) {
        lastCriteria().addCriterion("role_desc between", value1, value2, "roleDesc");
        return this;
    }

    public RoleCriteria andRoleDescNotBetween(String value1, String value2) {
        lastCriteria().addCriterion("role_desc not between", value1, value2, "roleDesc");
        return this;
    }

    public RoleCriteria andPermissionsIsNull() {
        lastCriteria().addCriterion("permissions is null");
        return this;
    }

    public RoleCriteria andPermissionsIsNotNull() {
        lastCriteria().addCriterion("permissions is not null");
        return this;
    }

    public RoleCriteria andPermissionsEqualTo(String value) {
        lastCriteria().addCriterion("permissions =", value, "permissions");
        return this;
    }

    public RoleCriteria andPermissionsNotEqualTo(String value) {
        lastCriteria().addCriterion("permissions <>", value, "permissions");
        return this;
    }

    public RoleCriteria andPermissionsGreaterThan(String value) {
        lastCriteria().addCriterion("permissions >", value, "permissions");
        return this;
    }

    public RoleCriteria andPermissionsGreaterThanOrEqualTo(String value) {
        lastCriteria().addCriterion("permissions >=", value, "permissions");
        return this;
    }

    public RoleCriteria andPermissionsLessThan(String value) {
        lastCriteria().addCriterion("permissions <", value, "permissions");
        return this;
    }

    public RoleCriteria andPermissionsLessThanOrEqualTo(String value) {
        lastCriteria().addCriterion("permissions <=", value, "permissions");
        return this;
    }

    public RoleCriteria andPermissionsLike(String value) {
        lastCriteria().addCriterion("permissions like", value, "permissions");
        return this;
    }

    public RoleCriteria andPermissionsNotLike(String value) {
        lastCriteria().addCriterion("permissions not like", value, "permissions");
        return this;
    }

    public RoleCriteria andPermissionsIn(List<String> values) {
        lastCriteria().addCriterion("permissions in", values, "permissions");
        return this;
    }

    public RoleCriteria andPermissionsNotIn(List<String> values) {
        lastCriteria().addCriterion("permissions not in", values, "permissions");
        return this;
    }

    public RoleCriteria andPermissionsBetween(String value1, String value2) {
        lastCriteria().addCriterion("permissions between", value1, value2, "permissions");
        return this;
    }

    public RoleCriteria andPermissionsNotBetween(String value1, String value2) {
        lastCriteria().addCriterion("permissions not between", value1, value2, "permissions");
        return this;
    }

    public RoleCriteria andCreateTimeIsNull() {
        lastCriteria().addCriterion("create_time is null");
        return this;
    }

    public RoleCriteria andCreateTimeIsNotNull() {
        lastCriteria().addCriterion("create_time is not null");
        return this;
    }

    public RoleCriteria andCreateTimeEqualTo(String value) {
        lastCriteria().addCriterion("create_time =", value, "createTime");
        return this;
    }

    public RoleCriteria andCreateTimeNotEqualTo(String value) {
        lastCriteria().addCriterion("create_time <>", value, "createTime");
        return this;
    }

    public RoleCriteria andCreateTimeGreaterThan(String value) {
        lastCriteria().addCriterion("create_time >", value, "createTime");
        return this;
    }

    public RoleCriteria andCreateTimeGreaterThanOrEqualTo(String value) {
        lastCriteria().addCriterion("create_time >=", value, "createTime");
        return this;
    }

    public RoleCriteria andCreateTimeLessThan(String value) {
        lastCriteria().addCriterion("create_time <", value, "createTime");
        return this;
    }

    public RoleCriteria andCreateTimeLessThanOrEqualTo(String value) {
        lastCriteria().addCriterion("create_time <=", value, "createTime");
        return this;
    }

    public RoleCriteria andCreateTimeLike(String value) {
        lastCriteria().addCriterion("create_time like", value, "createTime");
        return this;
    }

    public RoleCriteria andCreateTimeNotLike(String value) {
        lastCriteria().addCriterion("create_time not like", value, "createTime");
        return this;
    }

    public RoleCriteria andCreateTimeIn(List<String> values) {
        lastCriteria().addCriterion("create_time in", values, "createTime");
        return this;
    }

    public RoleCriteria andCreateTimeNotIn(List<String> values) {
        lastCriteria().addCriterion("create_time not in", values, "createTime");
        return this;
    }

    public RoleCriteria andCreateTimeBetween(String value1, String value2) {
        lastCriteria().addCriterion("create_time between", value1, value2, "createTime");
        return this;
    }

    public RoleCriteria andCreateTimeNotBetween(String value1, String value2) {
        lastCriteria().addCriterion("create_time not between", value1, value2, "createTime");
        return this;
    }

    public RoleCriteria andUpdateTimeIsNull() {
        lastCriteria().addCriterion("update_time is null");
        return this;
    }

    public RoleCriteria andUpdateTimeIsNotNull() {
        lastCriteria().addCriterion("update_time is not null");
        return this;
    }

    public RoleCriteria andUpdateTimeEqualTo(String value) {
        lastCriteria().addCriterion("update_time =", value, "updateTime");
        return this;
    }

    public RoleCriteria andUpdateTimeNotEqualTo(String value) {
        lastCriteria().addCriterion("update_time <>", value, "updateTime");
        return this;
    }

    public RoleCriteria andUpdateTimeGreaterThan(String value) {
        lastCriteria().addCriterion("update_time >", value, "updateTime");
        return this;
    }

    public RoleCriteria andUpdateTimeGreaterThanOrEqualTo(String value) {
        lastCriteria().addCriterion("update_time >=", value, "updateTime");
        return this;
    }

    public RoleCriteria andUpdateTimeLessThan(String value) {
        lastCriteria().addCriterion("update_time <", value, "updateTime");
        return this;
    }

    public RoleCriteria andUpdateTimeLessThanOrEqualTo(String value) {
        lastCriteria().addCriterion("update_time <=", value, "updateTime");
        return this;
    }

    public RoleCriteria andUpdateTimeLike(String value) {
        lastCriteria().addCriterion("update_time like", value, "updateTime");
        return this;
    }

    public RoleCriteria andUpdateTimeNotLike(String value) {
        lastCriteria().addCriterion("update_time not like", value, "updateTime");
        return this;
    }

    public RoleCriteria andUpdateTimeIn(List<String> values) {
        lastCriteria().addCriterion("update_time in", values, "updateTime");
        return this;
    }

    public RoleCriteria andUpdateTimeNotIn(List<String> values) {
        lastCriteria().addCriterion("update_time not in", values, "updateTime");
        return this;
    }

    public RoleCriteria andUpdateTimeBetween(String value1, String value2) {
        lastCriteria().addCriterion("update_time between", value1, value2, "updateTime");
        return this;
    }

    public RoleCriteria andUpdateTimeNotBetween(String value1, String value2) {
        lastCriteria().addCriterion("update_time not between", value1, value2, "updateTime");
        return this;
    }

    public RoleCriteria andRoleStatusIsNull() {
        lastCriteria().addCriterion("role_status is null");
        return this;
    }

    public RoleCriteria andRoleStatusIsNotNull() {
        lastCriteria().addCriterion("role_status is not null");
        return this;
    }

    public RoleCriteria andRoleStatusEqualTo(Integer value) {
        lastCriteria().addCriterion("role_status =", value, "roleStatus");
        return this;
    }

    public RoleCriteria andRoleStatusNotEqualTo(Integer value) {
        lastCriteria().addCriterion("role_status <>", value, "roleStatus");
        return this;
    }

    public RoleCriteria andRoleStatusGreaterThan(Integer value) {
        lastCriteria().addCriterion("role_status >", value, "roleStatus");
        return this;
    }

    public RoleCriteria andRoleStatusGreaterThanOrEqualTo(Integer value) {
        lastCriteria().addCriterion("role_status >=", value, "roleStatus");
        return this;
    }

    public RoleCriteria andRoleStatusLessThan(Integer value) {
        lastCriteria().addCriterion("role_status <", value, "roleStatus");
        return this;
    }

    public RoleCriteria andRoleStatusLessThanOrEqualTo(Integer value) {
        lastCriteria().addCriterion("role_status <=", value, "roleStatus");
        return this;
    }

    public RoleCriteria andRoleStatusIn(List<Integer> values) {
        lastCriteria().addCriterion("role_status in", values, "roleStatus");
        return this;
    }

    public RoleCriteria andRoleStatusNotIn(List<Integer> values) {
        lastCriteria().addCriterion("role_status not in", values, "roleStatus");
        return this;
    }

    public RoleCriteria andRoleStatusBetween(Integer value1, Integer value2) {
        lastCriteria().addCriterion("role_status between", value1, value2, "roleStatus");
        return this;
    }

    public RoleCriteria andRoleStatusNotBetween(Integer value1, Integer value2) {
        lastCriteria().addCriterion("role_status not between", value1, value2, "roleStatus");
        return this;
    }

    public static RoleCriteria idIsNull() {
        return new RoleCriteria().andIdIsNull();
    }

    public static RoleCriteria idIsNotNull() {
        return new RoleCriteria().andIdIsNotNull();
    }

    public static RoleCriteria idEqualTo(Integer value) {
        return new RoleCriteria().andIdEqualTo(value);
    }

    public static RoleCriteria idNotEqualTo(Integer value) {
        return new RoleCriteria().andIdNotEqualTo(value);
    }

    public static RoleCriteria idGreaterThan(Integer value) {
        return new RoleCriteria().andIdGreaterThan(value);
    }

    public static RoleCriteria idGreaterThanOrEqualTo(Integer value) {
        return new RoleCriteria().andIdGreaterThanOrEqualTo(value);
    }

    public static RoleCriteria idLessThan(Integer value) {
        return new RoleCriteria().andIdLessThan(value);
    }

    public static RoleCriteria idLessThanOrEqualTo(Integer value) {
        return new RoleCriteria().andIdLessThanOrEqualTo(value);
    }

    public static RoleCriteria idIn(List<Integer> values) {
        return new RoleCriteria().andIdIn(values);
    }

    public static RoleCriteria idNotIn(List<Integer> values) {
        return new RoleCriteria().andIdNotIn(values);
    }

    public static RoleCriteria idBetween(Integer value1, Integer value2) {
        return new RoleCriteria().andIdBetween(value1, value2);
    }

    public static RoleCriteria idNotBetween(Integer value1, Integer value2) {
        return new RoleCriteria().andIdNotBetween(value1, value2);
    }

    public static RoleCriteria roleNameIsNull() {
        return new RoleCriteria().andRoleNameIsNull();
    }

    public static RoleCriteria roleNameIsNotNull() {
        return new RoleCriteria().andRoleNameIsNotNull();
    }

    public static RoleCriteria roleNameEqualTo(String value) {
        return new RoleCriteria().andRoleNameEqualTo(value);
    }

    public static RoleCriteria roleNameNotEqualTo(String value) {
        return new RoleCriteria().andRoleNameNotEqualTo(value);
    }

    public static RoleCriteria roleNameGreaterThan(String value) {
        return new RoleCriteria().andRoleNameGreaterThan(value);
    }

    public static RoleCriteria roleNameGreaterThanOrEqualTo(String value) {
        return new RoleCriteria().andRoleNameGreaterThanOrEqualTo(value);
    }

    public static RoleCriteria roleNameLessThan(String value) {
        return new RoleCriteria().andRoleNameLessThan(value);
    }

    public static RoleCriteria roleNameLessThanOrEqualTo(String value) {
        return new RoleCriteria().andRoleNameLessThanOrEqualTo(value);
    }

    public static RoleCriteria roleNameLike(String value) {
        return new RoleCriteria().andRoleNameLike(value);
    }

    public static RoleCriteria roleNameNotLike(String value) {
        return new RoleCriteria().andRoleNameNotLike(value);
    }

    public static RoleCriteria roleNameIn(List<String> values) {
        return new RoleCriteria().andRoleNameIn(values);
    }

    public static RoleCriteria roleNameNotIn(List<String> values) {
        return new RoleCriteria().andRoleNameNotIn(values);
    }

    public static RoleCriteria roleNameBetween(String value1, String value2) {
        return new RoleCriteria().andRoleNameBetween(value1, value2);
    }

    public static RoleCriteria roleNameNotBetween(String value1, String value2) {
        return new RoleCriteria().andRoleNameNotBetween(value1, value2);
    }

    public static RoleCriteria roleDescIsNull() {
        return new RoleCriteria().andRoleDescIsNull();
    }

    public static RoleCriteria roleDescIsNotNull() {
        return new RoleCriteria().andRoleDescIsNotNull();
    }

    public static RoleCriteria roleDescEqualTo(String value) {
        return new RoleCriteria().andRoleDescEqualTo(value);
    }

    public static RoleCriteria roleDescNotEqualTo(String value) {
        return new RoleCriteria().andRoleDescNotEqualTo(value);
    }

    public static RoleCriteria roleDescGreaterThan(String value) {
        return new RoleCriteria().andRoleDescGreaterThan(value);
    }

    public static RoleCriteria roleDescGreaterThanOrEqualTo(String value) {
        return new RoleCriteria().andRoleDescGreaterThanOrEqualTo(value);
    }

    public static RoleCriteria roleDescLessThan(String value) {
        return new RoleCriteria().andRoleDescLessThan(value);
    }

    public static RoleCriteria roleDescLessThanOrEqualTo(String value) {
        return new RoleCriteria().andRoleDescLessThanOrEqualTo(value);
    }

    public static RoleCriteria roleDescLike(String value) {
        return new RoleCriteria().andRoleDescLike(value);
    }

    public static RoleCriteria roleDescNotLike(String value) {
        return new RoleCriteria().andRoleDescNotLike(value);
    }

    public static RoleCriteria roleDescIn(List<String> values) {
        return new RoleCriteria().andRoleDescIn(values);
    }

    public static RoleCriteria roleDescNotIn(List<String> values) {
        return new RoleCriteria().andRoleDescNotIn(values);
    }

    public static RoleCriteria roleDescBetween(String value1, String value2) {
        return new RoleCriteria().andRoleDescBetween(value1, value2);
    }

    public static RoleCriteria roleDescNotBetween(String value1, String value2) {
        return new RoleCriteria().andRoleDescNotBetween(value1, value2);
    }

    public static RoleCriteria permissionsIsNull() {
        return new RoleCriteria().andPermissionsIsNull();
    }

    public static RoleCriteria permissionsIsNotNull() {
        return new RoleCriteria().andPermissionsIsNotNull();
    }

    public static RoleCriteria permissionsEqualTo(String value) {
        return new RoleCriteria().andPermissionsEqualTo(value);
    }

    public static RoleCriteria permissionsNotEqualTo(String value) {
        return new RoleCriteria().andPermissionsNotEqualTo(value);
    }

    public static RoleCriteria permissionsGreaterThan(String value) {
        return new RoleCriteria().andPermissionsGreaterThan(value);
    }

    public static RoleCriteria permissionsGreaterThanOrEqualTo(String value) {
        return new RoleCriteria().andPermissionsGreaterThanOrEqualTo(value);
    }

    public static RoleCriteria permissionsLessThan(String value) {
        return new RoleCriteria().andPermissionsLessThan(value);
    }

    public static RoleCriteria permissionsLessThanOrEqualTo(String value) {
        return new RoleCriteria().andPermissionsLessThanOrEqualTo(value);
    }

    public static RoleCriteria permissionsLike(String value) {
        return new RoleCriteria().andPermissionsLike(value);
    }

    public static RoleCriteria permissionsNotLike(String value) {
        return new RoleCriteria().andPermissionsNotLike(value);
    }

    public static RoleCriteria permissionsIn(List<String> values) {
        return new RoleCriteria().andPermissionsIn(values);
    }

    public static RoleCriteria permissionsNotIn(List<String> values) {
        return new RoleCriteria().andPermissionsNotIn(values);
    }

    public static RoleCriteria permissionsBetween(String value1, String value2) {
        return new RoleCriteria().andPermissionsBetween(value1, value2);
    }

    public static RoleCriteria permissionsNotBetween(String value1, String value2) {
        return new RoleCriteria().andPermissionsNotBetween(value1, value2);
    }

    public static RoleCriteria createTimeIsNull() {
        return new RoleCriteria().andCreateTimeIsNull();
    }

    public static RoleCriteria createTimeIsNotNull() {
        return new RoleCriteria().andCreateTimeIsNotNull();
    }

    public static RoleCriteria createTimeEqualTo(String value) {
        return new RoleCriteria().andCreateTimeEqualTo(value);
    }

    public static RoleCriteria createTimeNotEqualTo(String value) {
        return new RoleCriteria().andCreateTimeNotEqualTo(value);
    }

    public static RoleCriteria createTimeGreaterThan(String value) {
        return new RoleCriteria().andCreateTimeGreaterThan(value);
    }

    public static RoleCriteria createTimeGreaterThanOrEqualTo(String value) {
        return new RoleCriteria().andCreateTimeGreaterThanOrEqualTo(value);
    }

    public static RoleCriteria createTimeLessThan(String value) {
        return new RoleCriteria().andCreateTimeLessThan(value);
    }

    public static RoleCriteria createTimeLessThanOrEqualTo(String value) {
        return new RoleCriteria().andCreateTimeLessThanOrEqualTo(value);
    }

    public static RoleCriteria createTimeLike(String value) {
        return new RoleCriteria().andCreateTimeLike(value);
    }

    public static RoleCriteria createTimeNotLike(String value) {
        return new RoleCriteria().andCreateTimeNotLike(value);
    }

    public static RoleCriteria createTimeIn(List<String> values) {
        return new RoleCriteria().andCreateTimeIn(values);
    }

    public static RoleCriteria createTimeNotIn(List<String> values) {
        return new RoleCriteria().andCreateTimeNotIn(values);
    }

    public static RoleCriteria createTimeBetween(String value1, String value2) {
        return new RoleCriteria().andCreateTimeBetween(value1, value2);
    }

    public static RoleCriteria createTimeNotBetween(String value1, String value2) {
        return new RoleCriteria().andCreateTimeNotBetween(value1, value2);
    }

    public static RoleCriteria updateTimeIsNull() {
        return new RoleCriteria().andUpdateTimeIsNull();
    }

    public static RoleCriteria updateTimeIsNotNull() {
        return new RoleCriteria().andUpdateTimeIsNotNull();
    }

    public static RoleCriteria updateTimeEqualTo(String value) {
        return new RoleCriteria().andUpdateTimeEqualTo(value);
    }

    public static RoleCriteria updateTimeNotEqualTo(String value) {
        return new RoleCriteria().andUpdateTimeNotEqualTo(value);
    }

    public static RoleCriteria updateTimeGreaterThan(String value) {
        return new RoleCriteria().andUpdateTimeGreaterThan(value);
    }

    public static RoleCriteria updateTimeGreaterThanOrEqualTo(String value) {
        return new RoleCriteria().andUpdateTimeGreaterThanOrEqualTo(value);
    }

    public static RoleCriteria updateTimeLessThan(String value) {
        return new RoleCriteria().andUpdateTimeLessThan(value);
    }

    public static RoleCriteria updateTimeLessThanOrEqualTo(String value) {
        return new RoleCriteria().andUpdateTimeLessThanOrEqualTo(value);
    }

    public static RoleCriteria updateTimeLike(String value) {
        return new RoleCriteria().andUpdateTimeLike(value);
    }

    public static RoleCriteria updateTimeNotLike(String value) {
        return new RoleCriteria().andUpdateTimeNotLike(value);
    }

    public static RoleCriteria updateTimeIn(List<String> values) {
        return new RoleCriteria().andUpdateTimeIn(values);
    }

    public static RoleCriteria updateTimeNotIn(List<String> values) {
        return new RoleCriteria().andUpdateTimeNotIn(values);
    }

    public static RoleCriteria updateTimeBetween(String value1, String value2) {
        return new RoleCriteria().andUpdateTimeBetween(value1, value2);
    }

    public static RoleCriteria updateTimeNotBetween(String value1, String value2) {
        return new RoleCriteria().andUpdateTimeNotBetween(value1, value2);
    }

    public static RoleCriteria roleStatusIsNull() {
        return new RoleCriteria().andRoleStatusIsNull();
    }

    public static RoleCriteria roleStatusIsNotNull() {
        return new RoleCriteria().andRoleStatusIsNotNull();
    }

    public static RoleCriteria roleStatusEqualTo(Integer value) {
        return new RoleCriteria().andRoleStatusEqualTo(value);
    }

    public static RoleCriteria roleStatusNotEqualTo(Integer value) {
        return new RoleCriteria().andRoleStatusNotEqualTo(value);
    }

    public static RoleCriteria roleStatusGreaterThan(Integer value) {
        return new RoleCriteria().andRoleStatusGreaterThan(value);
    }

    public static RoleCriteria roleStatusGreaterThanOrEqualTo(Integer value) {
        return new RoleCriteria().andRoleStatusGreaterThanOrEqualTo(value);
    }

    public static RoleCriteria roleStatusLessThan(Integer value) {
        return new RoleCriteria().andRoleStatusLessThan(value);
    }

    public static RoleCriteria roleStatusLessThanOrEqualTo(Integer value) {
        return new RoleCriteria().andRoleStatusLessThanOrEqualTo(value);
    }

    public static RoleCriteria roleStatusIn(List<Integer> values) {
        return new RoleCriteria().andRoleStatusIn(values);
    }

    public static RoleCriteria roleStatusNotIn(List<Integer> values) {
        return new RoleCriteria().andRoleStatusNotIn(values);
    }

    public static RoleCriteria roleStatusBetween(Integer value1, Integer value2) {
        return new RoleCriteria().andRoleStatusBetween(value1, value2);
    }

    public static RoleCriteria roleStatusNotBetween(Integer value1, Integer value2) {
        return new RoleCriteria().andRoleStatusNotBetween(value1, value2);
    }
}