package com.template.base.domain.criteria;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

// WARNING - @mbg.generated
// This file is automatically generated by MyBatis Generator, do not modify.
public class UserCriteria extends BaseCriteria {
    private static final Set<String> COLUMNS;

    static {
        COLUMNS = new HashSet<>();
        COLUMNS.add("id");
        COLUMNS.add("login_name");
        COLUMNS.add("login_password");
        COLUMNS.add("user_name");
        COLUMNS.add("create_time");
        COLUMNS.add("update_time");
        COLUMNS.add("del_flag");
    }

    public UserCriteria ascOrderBy(String  ... fields) {
        addOrderBy("asc", fields);
        return this;
    }

    public UserCriteria descOrderBy(String  ... fields) {
        addOrderBy("desc", fields);
        return this;
    }

    public UserCriteria or() {
        oredCriteria.add(new BracketCriteria());
        return this;
    }

    public UserCriteria setLimit(Long limit) {
        this.limit = limit;
        return this;
    }

    public UserCriteria setOffset(Long offset) {
        this.offset = offset;
        return this;
    }

    public UserCriteria setForUpdate(boolean forUpdate) {
        this.forUpdate = forUpdate;
        return this;
    }

    @Override
    protected boolean hasColumn(String column) {
        return COLUMNS.contains(column);
    }

    public UserCriteria andIdIsNull() {
        lastCriteria().addCriterion("id is null");
        return this;
    }

    public UserCriteria andIdIsNotNull() {
        lastCriteria().addCriterion("id is not null");
        return this;
    }

    public UserCriteria andIdEqualTo(Long value) {
        lastCriteria().addCriterion("id =", value, "id");
        return this;
    }

    public UserCriteria andIdNotEqualTo(Long value) {
        lastCriteria().addCriterion("id <>", value, "id");
        return this;
    }

    public UserCriteria andIdGreaterThan(Long value) {
        lastCriteria().addCriterion("id >", value, "id");
        return this;
    }

    public UserCriteria andIdGreaterThanOrEqualTo(Long value) {
        lastCriteria().addCriterion("id >=", value, "id");
        return this;
    }

    public UserCriteria andIdLessThan(Long value) {
        lastCriteria().addCriterion("id <", value, "id");
        return this;
    }

    public UserCriteria andIdLessThanOrEqualTo(Long value) {
        lastCriteria().addCriterion("id <=", value, "id");
        return this;
    }

    public UserCriteria andIdIn(List<Long> values) {
        lastCriteria().addCriterion("id in", values, "id");
        return this;
    }

    public UserCriteria andIdNotIn(List<Long> values) {
        lastCriteria().addCriterion("id not in", values, "id");
        return this;
    }

    public UserCriteria andIdBetween(Long value1, Long value2) {
        lastCriteria().addCriterion("id between", value1, value2, "id");
        return this;
    }

    public UserCriteria andIdNotBetween(Long value1, Long value2) {
        lastCriteria().addCriterion("id not between", value1, value2, "id");
        return this;
    }

    public UserCriteria andLoginNameIsNull() {
        lastCriteria().addCriterion("login_name is null");
        return this;
    }

    public UserCriteria andLoginNameIsNotNull() {
        lastCriteria().addCriterion("login_name is not null");
        return this;
    }

    public UserCriteria andLoginNameEqualTo(String value) {
        lastCriteria().addCriterion("login_name =", value, "loginName");
        return this;
    }

    public UserCriteria andLoginNameNotEqualTo(String value) {
        lastCriteria().addCriterion("login_name <>", value, "loginName");
        return this;
    }

    public UserCriteria andLoginNameGreaterThan(String value) {
        lastCriteria().addCriterion("login_name >", value, "loginName");
        return this;
    }

    public UserCriteria andLoginNameGreaterThanOrEqualTo(String value) {
        lastCriteria().addCriterion("login_name >=", value, "loginName");
        return this;
    }

    public UserCriteria andLoginNameLessThan(String value) {
        lastCriteria().addCriterion("login_name <", value, "loginName");
        return this;
    }

    public UserCriteria andLoginNameLessThanOrEqualTo(String value) {
        lastCriteria().addCriterion("login_name <=", value, "loginName");
        return this;
    }

    public UserCriteria andLoginNameLike(String value) {
        lastCriteria().addCriterion("login_name like", value, "loginName");
        return this;
    }

    public UserCriteria andLoginNameNotLike(String value) {
        lastCriteria().addCriterion("login_name not like", value, "loginName");
        return this;
    }

    public UserCriteria andLoginNameIn(List<String> values) {
        lastCriteria().addCriterion("login_name in", values, "loginName");
        return this;
    }

    public UserCriteria andLoginNameNotIn(List<String> values) {
        lastCriteria().addCriterion("login_name not in", values, "loginName");
        return this;
    }

    public UserCriteria andLoginNameBetween(String value1, String value2) {
        lastCriteria().addCriterion("login_name between", value1, value2, "loginName");
        return this;
    }

    public UserCriteria andLoginNameNotBetween(String value1, String value2) {
        lastCriteria().addCriterion("login_name not between", value1, value2, "loginName");
        return this;
    }

    public UserCriteria andLoginPasswordIsNull() {
        lastCriteria().addCriterion("login_password is null");
        return this;
    }

    public UserCriteria andLoginPasswordIsNotNull() {
        lastCriteria().addCriterion("login_password is not null");
        return this;
    }

    public UserCriteria andLoginPasswordEqualTo(String value) {
        lastCriteria().addCriterion("login_password =", value, "loginPassword");
        return this;
    }

    public UserCriteria andLoginPasswordNotEqualTo(String value) {
        lastCriteria().addCriterion("login_password <>", value, "loginPassword");
        return this;
    }

    public UserCriteria andLoginPasswordGreaterThan(String value) {
        lastCriteria().addCriterion("login_password >", value, "loginPassword");
        return this;
    }

    public UserCriteria andLoginPasswordGreaterThanOrEqualTo(String value) {
        lastCriteria().addCriterion("login_password >=", value, "loginPassword");
        return this;
    }

    public UserCriteria andLoginPasswordLessThan(String value) {
        lastCriteria().addCriterion("login_password <", value, "loginPassword");
        return this;
    }

    public UserCriteria andLoginPasswordLessThanOrEqualTo(String value) {
        lastCriteria().addCriterion("login_password <=", value, "loginPassword");
        return this;
    }

    public UserCriteria andLoginPasswordLike(String value) {
        lastCriteria().addCriterion("login_password like", value, "loginPassword");
        return this;
    }

    public UserCriteria andLoginPasswordNotLike(String value) {
        lastCriteria().addCriterion("login_password not like", value, "loginPassword");
        return this;
    }

    public UserCriteria andLoginPasswordIn(List<String> values) {
        lastCriteria().addCriterion("login_password in", values, "loginPassword");
        return this;
    }

    public UserCriteria andLoginPasswordNotIn(List<String> values) {
        lastCriteria().addCriterion("login_password not in", values, "loginPassword");
        return this;
    }

    public UserCriteria andLoginPasswordBetween(String value1, String value2) {
        lastCriteria().addCriterion("login_password between", value1, value2, "loginPassword");
        return this;
    }

    public UserCriteria andLoginPasswordNotBetween(String value1, String value2) {
        lastCriteria().addCriterion("login_password not between", value1, value2, "loginPassword");
        return this;
    }

    public UserCriteria andUserNameIsNull() {
        lastCriteria().addCriterion("user_name is null");
        return this;
    }

    public UserCriteria andUserNameIsNotNull() {
        lastCriteria().addCriterion("user_name is not null");
        return this;
    }

    public UserCriteria andUserNameEqualTo(String value) {
        lastCriteria().addCriterion("user_name =", value, "userName");
        return this;
    }

    public UserCriteria andUserNameNotEqualTo(String value) {
        lastCriteria().addCriterion("user_name <>", value, "userName");
        return this;
    }

    public UserCriteria andUserNameGreaterThan(String value) {
        lastCriteria().addCriterion("user_name >", value, "userName");
        return this;
    }

    public UserCriteria andUserNameGreaterThanOrEqualTo(String value) {
        lastCriteria().addCriterion("user_name >=", value, "userName");
        return this;
    }

    public UserCriteria andUserNameLessThan(String value) {
        lastCriteria().addCriterion("user_name <", value, "userName");
        return this;
    }

    public UserCriteria andUserNameLessThanOrEqualTo(String value) {
        lastCriteria().addCriterion("user_name <=", value, "userName");
        return this;
    }

    public UserCriteria andUserNameLike(String value) {
        lastCriteria().addCriterion("user_name like", value, "userName");
        return this;
    }

    public UserCriteria andUserNameNotLike(String value) {
        lastCriteria().addCriterion("user_name not like", value, "userName");
        return this;
    }

    public UserCriteria andUserNameIn(List<String> values) {
        lastCriteria().addCriterion("user_name in", values, "userName");
        return this;
    }

    public UserCriteria andUserNameNotIn(List<String> values) {
        lastCriteria().addCriterion("user_name not in", values, "userName");
        return this;
    }

    public UserCriteria andUserNameBetween(String value1, String value2) {
        lastCriteria().addCriterion("user_name between", value1, value2, "userName");
        return this;
    }

    public UserCriteria andUserNameNotBetween(String value1, String value2) {
        lastCriteria().addCriterion("user_name not between", value1, value2, "userName");
        return this;
    }

    public UserCriteria andCreateTimeIsNull() {
        lastCriteria().addCriterion("create_time is null");
        return this;
    }

    public UserCriteria andCreateTimeIsNotNull() {
        lastCriteria().addCriterion("create_time is not null");
        return this;
    }

    public UserCriteria andCreateTimeEqualTo(String value) {
        lastCriteria().addCriterion("create_time =", value, "createTime");
        return this;
    }

    public UserCriteria andCreateTimeNotEqualTo(String value) {
        lastCriteria().addCriterion("create_time <>", value, "createTime");
        return this;
    }

    public UserCriteria andCreateTimeGreaterThan(String value) {
        lastCriteria().addCriterion("create_time >", value, "createTime");
        return this;
    }

    public UserCriteria andCreateTimeGreaterThanOrEqualTo(String value) {
        lastCriteria().addCriterion("create_time >=", value, "createTime");
        return this;
    }

    public UserCriteria andCreateTimeLessThan(String value) {
        lastCriteria().addCriterion("create_time <", value, "createTime");
        return this;
    }

    public UserCriteria andCreateTimeLessThanOrEqualTo(String value) {
        lastCriteria().addCriterion("create_time <=", value, "createTime");
        return this;
    }

    public UserCriteria andCreateTimeLike(String value) {
        lastCriteria().addCriterion("create_time like", value, "createTime");
        return this;
    }

    public UserCriteria andCreateTimeNotLike(String value) {
        lastCriteria().addCriterion("create_time not like", value, "createTime");
        return this;
    }

    public UserCriteria andCreateTimeIn(List<String> values) {
        lastCriteria().addCriterion("create_time in", values, "createTime");
        return this;
    }

    public UserCriteria andCreateTimeNotIn(List<String> values) {
        lastCriteria().addCriterion("create_time not in", values, "createTime");
        return this;
    }

    public UserCriteria andCreateTimeBetween(String value1, String value2) {
        lastCriteria().addCriterion("create_time between", value1, value2, "createTime");
        return this;
    }

    public UserCriteria andCreateTimeNotBetween(String value1, String value2) {
        lastCriteria().addCriterion("create_time not between", value1, value2, "createTime");
        return this;
    }

    public UserCriteria andUpdateTimeIsNull() {
        lastCriteria().addCriterion("update_time is null");
        return this;
    }

    public UserCriteria andUpdateTimeIsNotNull() {
        lastCriteria().addCriterion("update_time is not null");
        return this;
    }

    public UserCriteria andUpdateTimeEqualTo(String value) {
        lastCriteria().addCriterion("update_time =", value, "updateTime");
        return this;
    }

    public UserCriteria andUpdateTimeNotEqualTo(String value) {
        lastCriteria().addCriterion("update_time <>", value, "updateTime");
        return this;
    }

    public UserCriteria andUpdateTimeGreaterThan(String value) {
        lastCriteria().addCriterion("update_time >", value, "updateTime");
        return this;
    }

    public UserCriteria andUpdateTimeGreaterThanOrEqualTo(String value) {
        lastCriteria().addCriterion("update_time >=", value, "updateTime");
        return this;
    }

    public UserCriteria andUpdateTimeLessThan(String value) {
        lastCriteria().addCriterion("update_time <", value, "updateTime");
        return this;
    }

    public UserCriteria andUpdateTimeLessThanOrEqualTo(String value) {
        lastCriteria().addCriterion("update_time <=", value, "updateTime");
        return this;
    }

    public UserCriteria andUpdateTimeLike(String value) {
        lastCriteria().addCriterion("update_time like", value, "updateTime");
        return this;
    }

    public UserCriteria andUpdateTimeNotLike(String value) {
        lastCriteria().addCriterion("update_time not like", value, "updateTime");
        return this;
    }

    public UserCriteria andUpdateTimeIn(List<String> values) {
        lastCriteria().addCriterion("update_time in", values, "updateTime");
        return this;
    }

    public UserCriteria andUpdateTimeNotIn(List<String> values) {
        lastCriteria().addCriterion("update_time not in", values, "updateTime");
        return this;
    }

    public UserCriteria andUpdateTimeBetween(String value1, String value2) {
        lastCriteria().addCriterion("update_time between", value1, value2, "updateTime");
        return this;
    }

    public UserCriteria andUpdateTimeNotBetween(String value1, String value2) {
        lastCriteria().addCriterion("update_time not between", value1, value2, "updateTime");
        return this;
    }

    public UserCriteria andDelFlagIsNull() {
        lastCriteria().addCriterion("del_flag is null");
        return this;
    }

    public UserCriteria andDelFlagIsNotNull() {
        lastCriteria().addCriterion("del_flag is not null");
        return this;
    }

    public UserCriteria andDelFlagEqualTo(Integer value) {
        lastCriteria().addCriterion("del_flag =", value, "delFlag");
        return this;
    }

    public UserCriteria andDelFlagNotEqualTo(Integer value) {
        lastCriteria().addCriterion("del_flag <>", value, "delFlag");
        return this;
    }

    public UserCriteria andDelFlagGreaterThan(Integer value) {
        lastCriteria().addCriterion("del_flag >", value, "delFlag");
        return this;
    }

    public UserCriteria andDelFlagGreaterThanOrEqualTo(Integer value) {
        lastCriteria().addCriterion("del_flag >=", value, "delFlag");
        return this;
    }

    public UserCriteria andDelFlagLessThan(Integer value) {
        lastCriteria().addCriterion("del_flag <", value, "delFlag");
        return this;
    }

    public UserCriteria andDelFlagLessThanOrEqualTo(Integer value) {
        lastCriteria().addCriterion("del_flag <=", value, "delFlag");
        return this;
    }

    public UserCriteria andDelFlagIn(List<Integer> values) {
        lastCriteria().addCriterion("del_flag in", values, "delFlag");
        return this;
    }

    public UserCriteria andDelFlagNotIn(List<Integer> values) {
        lastCriteria().addCriterion("del_flag not in", values, "delFlag");
        return this;
    }

    public UserCriteria andDelFlagBetween(Integer value1, Integer value2) {
        lastCriteria().addCriterion("del_flag between", value1, value2, "delFlag");
        return this;
    }

    public UserCriteria andDelFlagNotBetween(Integer value1, Integer value2) {
        lastCriteria().addCriterion("del_flag not between", value1, value2, "delFlag");
        return this;
    }

    public static UserCriteria idIsNull() {
        return new UserCriteria().andIdIsNull();
    }

    public static UserCriteria idIsNotNull() {
        return new UserCriteria().andIdIsNotNull();
    }

    public static UserCriteria idEqualTo(Long value) {
        return new UserCriteria().andIdEqualTo(value);
    }

    public static UserCriteria idNotEqualTo(Long value) {
        return new UserCriteria().andIdNotEqualTo(value);
    }

    public static UserCriteria idGreaterThan(Long value) {
        return new UserCriteria().andIdGreaterThan(value);
    }

    public static UserCriteria idGreaterThanOrEqualTo(Long value) {
        return new UserCriteria().andIdGreaterThanOrEqualTo(value);
    }

    public static UserCriteria idLessThan(Long value) {
        return new UserCriteria().andIdLessThan(value);
    }

    public static UserCriteria idLessThanOrEqualTo(Long value) {
        return new UserCriteria().andIdLessThanOrEqualTo(value);
    }

    public static UserCriteria idIn(List<Long> values) {
        return new UserCriteria().andIdIn(values);
    }

    public static UserCriteria idNotIn(List<Long> values) {
        return new UserCriteria().andIdNotIn(values);
    }

    public static UserCriteria idBetween(Long value1, Long value2) {
        return new UserCriteria().andIdBetween(value1, value2);
    }

    public static UserCriteria idNotBetween(Long value1, Long value2) {
        return new UserCriteria().andIdNotBetween(value1, value2);
    }

    public static UserCriteria loginNameIsNull() {
        return new UserCriteria().andLoginNameIsNull();
    }

    public static UserCriteria loginNameIsNotNull() {
        return new UserCriteria().andLoginNameIsNotNull();
    }

    public static UserCriteria loginNameEqualTo(String value) {
        return new UserCriteria().andLoginNameEqualTo(value);
    }

    public static UserCriteria loginNameNotEqualTo(String value) {
        return new UserCriteria().andLoginNameNotEqualTo(value);
    }

    public static UserCriteria loginNameGreaterThan(String value) {
        return new UserCriteria().andLoginNameGreaterThan(value);
    }

    public static UserCriteria loginNameGreaterThanOrEqualTo(String value) {
        return new UserCriteria().andLoginNameGreaterThanOrEqualTo(value);
    }

    public static UserCriteria loginNameLessThan(String value) {
        return new UserCriteria().andLoginNameLessThan(value);
    }

    public static UserCriteria loginNameLessThanOrEqualTo(String value) {
        return new UserCriteria().andLoginNameLessThanOrEqualTo(value);
    }

    public static UserCriteria loginNameLike(String value) {
        return new UserCriteria().andLoginNameLike(value);
    }

    public static UserCriteria loginNameNotLike(String value) {
        return new UserCriteria().andLoginNameNotLike(value);
    }

    public static UserCriteria loginNameIn(List<String> values) {
        return new UserCriteria().andLoginNameIn(values);
    }

    public static UserCriteria loginNameNotIn(List<String> values) {
        return new UserCriteria().andLoginNameNotIn(values);
    }

    public static UserCriteria loginNameBetween(String value1, String value2) {
        return new UserCriteria().andLoginNameBetween(value1, value2);
    }

    public static UserCriteria loginNameNotBetween(String value1, String value2) {
        return new UserCriteria().andLoginNameNotBetween(value1, value2);
    }

    public static UserCriteria loginPasswordIsNull() {
        return new UserCriteria().andLoginPasswordIsNull();
    }

    public static UserCriteria loginPasswordIsNotNull() {
        return new UserCriteria().andLoginPasswordIsNotNull();
    }

    public static UserCriteria loginPasswordEqualTo(String value) {
        return new UserCriteria().andLoginPasswordEqualTo(value);
    }

    public static UserCriteria loginPasswordNotEqualTo(String value) {
        return new UserCriteria().andLoginPasswordNotEqualTo(value);
    }

    public static UserCriteria loginPasswordGreaterThan(String value) {
        return new UserCriteria().andLoginPasswordGreaterThan(value);
    }

    public static UserCriteria loginPasswordGreaterThanOrEqualTo(String value) {
        return new UserCriteria().andLoginPasswordGreaterThanOrEqualTo(value);
    }

    public static UserCriteria loginPasswordLessThan(String value) {
        return new UserCriteria().andLoginPasswordLessThan(value);
    }

    public static UserCriteria loginPasswordLessThanOrEqualTo(String value) {
        return new UserCriteria().andLoginPasswordLessThanOrEqualTo(value);
    }

    public static UserCriteria loginPasswordLike(String value) {
        return new UserCriteria().andLoginPasswordLike(value);
    }

    public static UserCriteria loginPasswordNotLike(String value) {
        return new UserCriteria().andLoginPasswordNotLike(value);
    }

    public static UserCriteria loginPasswordIn(List<String> values) {
        return new UserCriteria().andLoginPasswordIn(values);
    }

    public static UserCriteria loginPasswordNotIn(List<String> values) {
        return new UserCriteria().andLoginPasswordNotIn(values);
    }

    public static UserCriteria loginPasswordBetween(String value1, String value2) {
        return new UserCriteria().andLoginPasswordBetween(value1, value2);
    }

    public static UserCriteria loginPasswordNotBetween(String value1, String value2) {
        return new UserCriteria().andLoginPasswordNotBetween(value1, value2);
    }

    public static UserCriteria userNameIsNull() {
        return new UserCriteria().andUserNameIsNull();
    }

    public static UserCriteria userNameIsNotNull() {
        return new UserCriteria().andUserNameIsNotNull();
    }

    public static UserCriteria userNameEqualTo(String value) {
        return new UserCriteria().andUserNameEqualTo(value);
    }

    public static UserCriteria userNameNotEqualTo(String value) {
        return new UserCriteria().andUserNameNotEqualTo(value);
    }

    public static UserCriteria userNameGreaterThan(String value) {
        return new UserCriteria().andUserNameGreaterThan(value);
    }

    public static UserCriteria userNameGreaterThanOrEqualTo(String value) {
        return new UserCriteria().andUserNameGreaterThanOrEqualTo(value);
    }

    public static UserCriteria userNameLessThan(String value) {
        return new UserCriteria().andUserNameLessThan(value);
    }

    public static UserCriteria userNameLessThanOrEqualTo(String value) {
        return new UserCriteria().andUserNameLessThanOrEqualTo(value);
    }

    public static UserCriteria userNameLike(String value) {
        return new UserCriteria().andUserNameLike(value);
    }

    public static UserCriteria userNameNotLike(String value) {
        return new UserCriteria().andUserNameNotLike(value);
    }

    public static UserCriteria userNameIn(List<String> values) {
        return new UserCriteria().andUserNameIn(values);
    }

    public static UserCriteria userNameNotIn(List<String> values) {
        return new UserCriteria().andUserNameNotIn(values);
    }

    public static UserCriteria userNameBetween(String value1, String value2) {
        return new UserCriteria().andUserNameBetween(value1, value2);
    }

    public static UserCriteria userNameNotBetween(String value1, String value2) {
        return new UserCriteria().andUserNameNotBetween(value1, value2);
    }

    public static UserCriteria createTimeIsNull() {
        return new UserCriteria().andCreateTimeIsNull();
    }

    public static UserCriteria createTimeIsNotNull() {
        return new UserCriteria().andCreateTimeIsNotNull();
    }

    public static UserCriteria createTimeEqualTo(String value) {
        return new UserCriteria().andCreateTimeEqualTo(value);
    }

    public static UserCriteria createTimeNotEqualTo(String value) {
        return new UserCriteria().andCreateTimeNotEqualTo(value);
    }

    public static UserCriteria createTimeGreaterThan(String value) {
        return new UserCriteria().andCreateTimeGreaterThan(value);
    }

    public static UserCriteria createTimeGreaterThanOrEqualTo(String value) {
        return new UserCriteria().andCreateTimeGreaterThanOrEqualTo(value);
    }

    public static UserCriteria createTimeLessThan(String value) {
        return new UserCriteria().andCreateTimeLessThan(value);
    }

    public static UserCriteria createTimeLessThanOrEqualTo(String value) {
        return new UserCriteria().andCreateTimeLessThanOrEqualTo(value);
    }

    public static UserCriteria createTimeLike(String value) {
        return new UserCriteria().andCreateTimeLike(value);
    }

    public static UserCriteria createTimeNotLike(String value) {
        return new UserCriteria().andCreateTimeNotLike(value);
    }

    public static UserCriteria createTimeIn(List<String> values) {
        return new UserCriteria().andCreateTimeIn(values);
    }

    public static UserCriteria createTimeNotIn(List<String> values) {
        return new UserCriteria().andCreateTimeNotIn(values);
    }

    public static UserCriteria createTimeBetween(String value1, String value2) {
        return new UserCriteria().andCreateTimeBetween(value1, value2);
    }

    public static UserCriteria createTimeNotBetween(String value1, String value2) {
        return new UserCriteria().andCreateTimeNotBetween(value1, value2);
    }

    public static UserCriteria updateTimeIsNull() {
        return new UserCriteria().andUpdateTimeIsNull();
    }

    public static UserCriteria updateTimeIsNotNull() {
        return new UserCriteria().andUpdateTimeIsNotNull();
    }

    public static UserCriteria updateTimeEqualTo(String value) {
        return new UserCriteria().andUpdateTimeEqualTo(value);
    }

    public static UserCriteria updateTimeNotEqualTo(String value) {
        return new UserCriteria().andUpdateTimeNotEqualTo(value);
    }

    public static UserCriteria updateTimeGreaterThan(String value) {
        return new UserCriteria().andUpdateTimeGreaterThan(value);
    }

    public static UserCriteria updateTimeGreaterThanOrEqualTo(String value) {
        return new UserCriteria().andUpdateTimeGreaterThanOrEqualTo(value);
    }

    public static UserCriteria updateTimeLessThan(String value) {
        return new UserCriteria().andUpdateTimeLessThan(value);
    }

    public static UserCriteria updateTimeLessThanOrEqualTo(String value) {
        return new UserCriteria().andUpdateTimeLessThanOrEqualTo(value);
    }

    public static UserCriteria updateTimeLike(String value) {
        return new UserCriteria().andUpdateTimeLike(value);
    }

    public static UserCriteria updateTimeNotLike(String value) {
        return new UserCriteria().andUpdateTimeNotLike(value);
    }

    public static UserCriteria updateTimeIn(List<String> values) {
        return new UserCriteria().andUpdateTimeIn(values);
    }

    public static UserCriteria updateTimeNotIn(List<String> values) {
        return new UserCriteria().andUpdateTimeNotIn(values);
    }

    public static UserCriteria updateTimeBetween(String value1, String value2) {
        return new UserCriteria().andUpdateTimeBetween(value1, value2);
    }

    public static UserCriteria updateTimeNotBetween(String value1, String value2) {
        return new UserCriteria().andUpdateTimeNotBetween(value1, value2);
    }

    public static UserCriteria delFlagIsNull() {
        return new UserCriteria().andDelFlagIsNull();
    }

    public static UserCriteria delFlagIsNotNull() {
        return new UserCriteria().andDelFlagIsNotNull();
    }

    public static UserCriteria delFlagEqualTo(Integer value) {
        return new UserCriteria().andDelFlagEqualTo(value);
    }

    public static UserCriteria delFlagNotEqualTo(Integer value) {
        return new UserCriteria().andDelFlagNotEqualTo(value);
    }

    public static UserCriteria delFlagGreaterThan(Integer value) {
        return new UserCriteria().andDelFlagGreaterThan(value);
    }

    public static UserCriteria delFlagGreaterThanOrEqualTo(Integer value) {
        return new UserCriteria().andDelFlagGreaterThanOrEqualTo(value);
    }

    public static UserCriteria delFlagLessThan(Integer value) {
        return new UserCriteria().andDelFlagLessThan(value);
    }

    public static UserCriteria delFlagLessThanOrEqualTo(Integer value) {
        return new UserCriteria().andDelFlagLessThanOrEqualTo(value);
    }

    public static UserCriteria delFlagIn(List<Integer> values) {
        return new UserCriteria().andDelFlagIn(values);
    }

    public static UserCriteria delFlagNotIn(List<Integer> values) {
        return new UserCriteria().andDelFlagNotIn(values);
    }

    public static UserCriteria delFlagBetween(Integer value1, Integer value2) {
        return new UserCriteria().andDelFlagBetween(value1, value2);
    }

    public static UserCriteria delFlagNotBetween(Integer value1, Integer value2) {
        return new UserCriteria().andDelFlagNotBetween(value1, value2);
    }
}