package com.template.demo.base.domain.criteria;

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

// WARNING - @mbg.generated
// This file is automatically generated by MyBatis Generator, do not modify.
public class TemplateMemberCriteria extends BaseCriteria {
    private static final Set<String> COLUMNS;

    static {
        COLUMNS = new HashSet<>();
        COLUMNS.add("id");
        COLUMNS.add("login_name");
        COLUMNS.add("login_password");
        COLUMNS.add("create_time");
        COLUMNS.add("update_time");
    }

    public TemplateMemberCriteria ascOrderBy(String  ... fields) {
        addOrderBy("asc", fields);
        return this;
    }

    public TemplateMemberCriteria descOrderBy(String  ... fields) {
        addOrderBy("desc", fields);
        return this;
    }

    public TemplateMemberCriteria or() {
        oredCriteria.add(new BracketCriteria());
        return this;
    }

    public TemplateMemberCriteria setLimit(Long limit) {
        this.limit = limit;
        return this;
    }

    public TemplateMemberCriteria setOffset(Long offset) {
        this.offset = offset;
        return this;
    }

    public TemplateMemberCriteria setForUpdate(boolean forUpdate) {
        this.forUpdate = forUpdate;
        return this;
    }

    @Override
    protected boolean hasColumn(String column) {
        return COLUMNS.contains(column);
    }

    public TemplateMemberCriteria andIdIsNull() {
        lastCriteria().addCriterion("id is null");
        return this;
    }

    public TemplateMemberCriteria andIdIsNotNull() {
        lastCriteria().addCriterion("id is not null");
        return this;
    }

    public TemplateMemberCriteria andIdEqualTo(Long value) {
        lastCriteria().addCriterion("id =", value, "id");
        return this;
    }

    public TemplateMemberCriteria andIdNotEqualTo(Long value) {
        lastCriteria().addCriterion("id <>", value, "id");
        return this;
    }

    public TemplateMemberCriteria andIdGreaterThan(Long value) {
        lastCriteria().addCriterion("id >", value, "id");
        return this;
    }

    public TemplateMemberCriteria andIdGreaterThanOrEqualTo(Long value) {
        lastCriteria().addCriterion("id >=", value, "id");
        return this;
    }

    public TemplateMemberCriteria andIdLessThan(Long value) {
        lastCriteria().addCriterion("id <", value, "id");
        return this;
    }

    public TemplateMemberCriteria andIdLessThanOrEqualTo(Long value) {
        lastCriteria().addCriterion("id <=", value, "id");
        return this;
    }

    public TemplateMemberCriteria andIdIn(List<Long> values) {
        lastCriteria().addCriterion("id in", values, "id");
        return this;
    }

    public TemplateMemberCriteria andIdNotIn(List<Long> values) {
        lastCriteria().addCriterion("id not in", values, "id");
        return this;
    }

    public TemplateMemberCriteria andIdBetween(Long value1, Long value2) {
        lastCriteria().addCriterion("id between", value1, value2, "id");
        return this;
    }

    public TemplateMemberCriteria andIdNotBetween(Long value1, Long value2) {
        lastCriteria().addCriterion("id not between", value1, value2, "id");
        return this;
    }

    public TemplateMemberCriteria andLoginNameIsNull() {
        lastCriteria().addCriterion("login_name is null");
        return this;
    }

    public TemplateMemberCriteria andLoginNameIsNotNull() {
        lastCriteria().addCriterion("login_name is not null");
        return this;
    }

    public TemplateMemberCriteria andLoginNameEqualTo(String value) {
        lastCriteria().addCriterion("login_name =", value, "loginName");
        return this;
    }

    public TemplateMemberCriteria andLoginNameNotEqualTo(String value) {
        lastCriteria().addCriterion("login_name <>", value, "loginName");
        return this;
    }

    public TemplateMemberCriteria andLoginNameGreaterThan(String value) {
        lastCriteria().addCriterion("login_name >", value, "loginName");
        return this;
    }

    public TemplateMemberCriteria andLoginNameGreaterThanOrEqualTo(String value) {
        lastCriteria().addCriterion("login_name >=", value, "loginName");
        return this;
    }

    public TemplateMemberCriteria andLoginNameLessThan(String value) {
        lastCriteria().addCriterion("login_name <", value, "loginName");
        return this;
    }

    public TemplateMemberCriteria andLoginNameLessThanOrEqualTo(String value) {
        lastCriteria().addCriterion("login_name <=", value, "loginName");
        return this;
    }

    public TemplateMemberCriteria andLoginNameLike(String value) {
        lastCriteria().addCriterion("login_name like", value, "loginName");
        return this;
    }

    public TemplateMemberCriteria andLoginNameNotLike(String value) {
        lastCriteria().addCriterion("login_name not like", value, "loginName");
        return this;
    }

    public TemplateMemberCriteria andLoginNameIn(List<String> values) {
        lastCriteria().addCriterion("login_name in", values, "loginName");
        return this;
    }

    public TemplateMemberCriteria andLoginNameNotIn(List<String> values) {
        lastCriteria().addCriterion("login_name not in", values, "loginName");
        return this;
    }

    public TemplateMemberCriteria andLoginNameBetween(String value1, String value2) {
        lastCriteria().addCriterion("login_name between", value1, value2, "loginName");
        return this;
    }

    public TemplateMemberCriteria andLoginNameNotBetween(String value1, String value2) {
        lastCriteria().addCriterion("login_name not between", value1, value2, "loginName");
        return this;
    }

    public TemplateMemberCriteria andLoginPasswordIsNull() {
        lastCriteria().addCriterion("login_password is null");
        return this;
    }

    public TemplateMemberCriteria andLoginPasswordIsNotNull() {
        lastCriteria().addCriterion("login_password is not null");
        return this;
    }

    public TemplateMemberCriteria andLoginPasswordEqualTo(String value) {
        lastCriteria().addCriterion("login_password =", value, "loginPassword");
        return this;
    }

    public TemplateMemberCriteria andLoginPasswordNotEqualTo(String value) {
        lastCriteria().addCriterion("login_password <>", value, "loginPassword");
        return this;
    }

    public TemplateMemberCriteria andLoginPasswordGreaterThan(String value) {
        lastCriteria().addCriterion("login_password >", value, "loginPassword");
        return this;
    }

    public TemplateMemberCriteria andLoginPasswordGreaterThanOrEqualTo(String value) {
        lastCriteria().addCriterion("login_password >=", value, "loginPassword");
        return this;
    }

    public TemplateMemberCriteria andLoginPasswordLessThan(String value) {
        lastCriteria().addCriterion("login_password <", value, "loginPassword");
        return this;
    }

    public TemplateMemberCriteria andLoginPasswordLessThanOrEqualTo(String value) {
        lastCriteria().addCriterion("login_password <=", value, "loginPassword");
        return this;
    }

    public TemplateMemberCriteria andLoginPasswordLike(String value) {
        lastCriteria().addCriterion("login_password like", value, "loginPassword");
        return this;
    }

    public TemplateMemberCriteria andLoginPasswordNotLike(String value) {
        lastCriteria().addCriterion("login_password not like", value, "loginPassword");
        return this;
    }

    public TemplateMemberCriteria andLoginPasswordIn(List<String> values) {
        lastCriteria().addCriterion("login_password in", values, "loginPassword");
        return this;
    }

    public TemplateMemberCriteria andLoginPasswordNotIn(List<String> values) {
        lastCriteria().addCriterion("login_password not in", values, "loginPassword");
        return this;
    }

    public TemplateMemberCriteria andLoginPasswordBetween(String value1, String value2) {
        lastCriteria().addCriterion("login_password between", value1, value2, "loginPassword");
        return this;
    }

    public TemplateMemberCriteria andLoginPasswordNotBetween(String value1, String value2) {
        lastCriteria().addCriterion("login_password not between", value1, value2, "loginPassword");
        return this;
    }

    public TemplateMemberCriteria andCreateTimeIsNull() {
        lastCriteria().addCriterion("create_time is null");
        return this;
    }

    public TemplateMemberCriteria andCreateTimeIsNotNull() {
        lastCriteria().addCriterion("create_time is not null");
        return this;
    }

    public TemplateMemberCriteria andCreateTimeEqualTo(Date value) {
        lastCriteria().addCriterion("create_time =", value, "createTime");
        return this;
    }

    public TemplateMemberCriteria andCreateTimeNotEqualTo(Date value) {
        lastCriteria().addCriterion("create_time <>", value, "createTime");
        return this;
    }

    public TemplateMemberCriteria andCreateTimeGreaterThan(Date value) {
        lastCriteria().addCriterion("create_time >", value, "createTime");
        return this;
    }

    public TemplateMemberCriteria andCreateTimeGreaterThanOrEqualTo(Date value) {
        lastCriteria().addCriterion("create_time >=", value, "createTime");
        return this;
    }

    public TemplateMemberCriteria andCreateTimeLessThan(Date value) {
        lastCriteria().addCriterion("create_time <", value, "createTime");
        return this;
    }

    public TemplateMemberCriteria andCreateTimeLessThanOrEqualTo(Date value) {
        lastCriteria().addCriterion("create_time <=", value, "createTime");
        return this;
    }

    public TemplateMemberCriteria andCreateTimeIn(List<Date> values) {
        lastCriteria().addCriterion("create_time in", values, "createTime");
        return this;
    }

    public TemplateMemberCriteria andCreateTimeNotIn(List<Date> values) {
        lastCriteria().addCriterion("create_time not in", values, "createTime");
        return this;
    }

    public TemplateMemberCriteria andCreateTimeBetween(Date value1, Date value2) {
        lastCriteria().addCriterion("create_time between", value1, value2, "createTime");
        return this;
    }

    public TemplateMemberCriteria andCreateTimeNotBetween(Date value1, Date value2) {
        lastCriteria().addCriterion("create_time not between", value1, value2, "createTime");
        return this;
    }

    public TemplateMemberCriteria andUpdateTimeIsNull() {
        lastCriteria().addCriterion("update_time is null");
        return this;
    }

    public TemplateMemberCriteria andUpdateTimeIsNotNull() {
        lastCriteria().addCriterion("update_time is not null");
        return this;
    }

    public TemplateMemberCriteria andUpdateTimeEqualTo(Date value) {
        lastCriteria().addCriterion("update_time =", value, "updateTime");
        return this;
    }

    public TemplateMemberCriteria andUpdateTimeNotEqualTo(Date value) {
        lastCriteria().addCriterion("update_time <>", value, "updateTime");
        return this;
    }

    public TemplateMemberCriteria andUpdateTimeGreaterThan(Date value) {
        lastCriteria().addCriterion("update_time >", value, "updateTime");
        return this;
    }

    public TemplateMemberCriteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
        lastCriteria().addCriterion("update_time >=", value, "updateTime");
        return this;
    }

    public TemplateMemberCriteria andUpdateTimeLessThan(Date value) {
        lastCriteria().addCriterion("update_time <", value, "updateTime");
        return this;
    }

    public TemplateMemberCriteria andUpdateTimeLessThanOrEqualTo(Date value) {
        lastCriteria().addCriterion("update_time <=", value, "updateTime");
        return this;
    }

    public TemplateMemberCriteria andUpdateTimeIn(List<Date> values) {
        lastCriteria().addCriterion("update_time in", values, "updateTime");
        return this;
    }

    public TemplateMemberCriteria andUpdateTimeNotIn(List<Date> values) {
        lastCriteria().addCriterion("update_time not in", values, "updateTime");
        return this;
    }

    public TemplateMemberCriteria andUpdateTimeBetween(Date value1, Date value2) {
        lastCriteria().addCriterion("update_time between", value1, value2, "updateTime");
        return this;
    }

    public TemplateMemberCriteria andUpdateTimeNotBetween(Date value1, Date value2) {
        lastCriteria().addCriterion("update_time not between", value1, value2, "updateTime");
        return this;
    }

    public static TemplateMemberCriteria idIsNull() {
        return new TemplateMemberCriteria().andIdIsNull();
    }

    public static TemplateMemberCriteria idIsNotNull() {
        return new TemplateMemberCriteria().andIdIsNotNull();
    }

    public static TemplateMemberCriteria idEqualTo(Long value) {
        return new TemplateMemberCriteria().andIdEqualTo(value);
    }

    public static TemplateMemberCriteria idNotEqualTo(Long value) {
        return new TemplateMemberCriteria().andIdNotEqualTo(value);
    }

    public static TemplateMemberCriteria idGreaterThan(Long value) {
        return new TemplateMemberCriteria().andIdGreaterThan(value);
    }

    public static TemplateMemberCriteria idGreaterThanOrEqualTo(Long value) {
        return new TemplateMemberCriteria().andIdGreaterThanOrEqualTo(value);
    }

    public static TemplateMemberCriteria idLessThan(Long value) {
        return new TemplateMemberCriteria().andIdLessThan(value);
    }

    public static TemplateMemberCriteria idLessThanOrEqualTo(Long value) {
        return new TemplateMemberCriteria().andIdLessThanOrEqualTo(value);
    }

    public static TemplateMemberCriteria idIn(List<Long> values) {
        return new TemplateMemberCriteria().andIdIn(values);
    }

    public static TemplateMemberCriteria idNotIn(List<Long> values) {
        return new TemplateMemberCriteria().andIdNotIn(values);
    }

    public static TemplateMemberCriteria idBetween(Long value1, Long value2) {
        return new TemplateMemberCriteria().andIdBetween(value1, value2);
    }

    public static TemplateMemberCriteria idNotBetween(Long value1, Long value2) {
        return new TemplateMemberCriteria().andIdNotBetween(value1, value2);
    }

    public static TemplateMemberCriteria loginNameIsNull() {
        return new TemplateMemberCriteria().andLoginNameIsNull();
    }

    public static TemplateMemberCriteria loginNameIsNotNull() {
        return new TemplateMemberCriteria().andLoginNameIsNotNull();
    }

    public static TemplateMemberCriteria loginNameEqualTo(String value) {
        return new TemplateMemberCriteria().andLoginNameEqualTo(value);
    }

    public static TemplateMemberCriteria loginNameNotEqualTo(String value) {
        return new TemplateMemberCriteria().andLoginNameNotEqualTo(value);
    }

    public static TemplateMemberCriteria loginNameGreaterThan(String value) {
        return new TemplateMemberCriteria().andLoginNameGreaterThan(value);
    }

    public static TemplateMemberCriteria loginNameGreaterThanOrEqualTo(String value) {
        return new TemplateMemberCriteria().andLoginNameGreaterThanOrEqualTo(value);
    }

    public static TemplateMemberCriteria loginNameLessThan(String value) {
        return new TemplateMemberCriteria().andLoginNameLessThan(value);
    }

    public static TemplateMemberCriteria loginNameLessThanOrEqualTo(String value) {
        return new TemplateMemberCriteria().andLoginNameLessThanOrEqualTo(value);
    }

    public static TemplateMemberCriteria loginNameLike(String value) {
        return new TemplateMemberCriteria().andLoginNameLike(value);
    }

    public static TemplateMemberCriteria loginNameNotLike(String value) {
        return new TemplateMemberCriteria().andLoginNameNotLike(value);
    }

    public static TemplateMemberCriteria loginNameIn(List<String> values) {
        return new TemplateMemberCriteria().andLoginNameIn(values);
    }

    public static TemplateMemberCriteria loginNameNotIn(List<String> values) {
        return new TemplateMemberCriteria().andLoginNameNotIn(values);
    }

    public static TemplateMemberCriteria loginNameBetween(String value1, String value2) {
        return new TemplateMemberCriteria().andLoginNameBetween(value1, value2);
    }

    public static TemplateMemberCriteria loginNameNotBetween(String value1, String value2) {
        return new TemplateMemberCriteria().andLoginNameNotBetween(value1, value2);
    }

    public static TemplateMemberCriteria loginPasswordIsNull() {
        return new TemplateMemberCriteria().andLoginPasswordIsNull();
    }

    public static TemplateMemberCriteria loginPasswordIsNotNull() {
        return new TemplateMemberCriteria().andLoginPasswordIsNotNull();
    }

    public static TemplateMemberCriteria loginPasswordEqualTo(String value) {
        return new TemplateMemberCriteria().andLoginPasswordEqualTo(value);
    }

    public static TemplateMemberCriteria loginPasswordNotEqualTo(String value) {
        return new TemplateMemberCriteria().andLoginPasswordNotEqualTo(value);
    }

    public static TemplateMemberCriteria loginPasswordGreaterThan(String value) {
        return new TemplateMemberCriteria().andLoginPasswordGreaterThan(value);
    }

    public static TemplateMemberCriteria loginPasswordGreaterThanOrEqualTo(String value) {
        return new TemplateMemberCriteria().andLoginPasswordGreaterThanOrEqualTo(value);
    }

    public static TemplateMemberCriteria loginPasswordLessThan(String value) {
        return new TemplateMemberCriteria().andLoginPasswordLessThan(value);
    }

    public static TemplateMemberCriteria loginPasswordLessThanOrEqualTo(String value) {
        return new TemplateMemberCriteria().andLoginPasswordLessThanOrEqualTo(value);
    }

    public static TemplateMemberCriteria loginPasswordLike(String value) {
        return new TemplateMemberCriteria().andLoginPasswordLike(value);
    }

    public static TemplateMemberCriteria loginPasswordNotLike(String value) {
        return new TemplateMemberCriteria().andLoginPasswordNotLike(value);
    }

    public static TemplateMemberCriteria loginPasswordIn(List<String> values) {
        return new TemplateMemberCriteria().andLoginPasswordIn(values);
    }

    public static TemplateMemberCriteria loginPasswordNotIn(List<String> values) {
        return new TemplateMemberCriteria().andLoginPasswordNotIn(values);
    }

    public static TemplateMemberCriteria loginPasswordBetween(String value1, String value2) {
        return new TemplateMemberCriteria().andLoginPasswordBetween(value1, value2);
    }

    public static TemplateMemberCriteria loginPasswordNotBetween(String value1, String value2) {
        return new TemplateMemberCriteria().andLoginPasswordNotBetween(value1, value2);
    }

    public static TemplateMemberCriteria createTimeIsNull() {
        return new TemplateMemberCriteria().andCreateTimeIsNull();
    }

    public static TemplateMemberCriteria createTimeIsNotNull() {
        return new TemplateMemberCriteria().andCreateTimeIsNotNull();
    }

    public static TemplateMemberCriteria createTimeEqualTo(Date value) {
        return new TemplateMemberCriteria().andCreateTimeEqualTo(value);
    }

    public static TemplateMemberCriteria createTimeNotEqualTo(Date value) {
        return new TemplateMemberCriteria().andCreateTimeNotEqualTo(value);
    }

    public static TemplateMemberCriteria createTimeGreaterThan(Date value) {
        return new TemplateMemberCriteria().andCreateTimeGreaterThan(value);
    }

    public static TemplateMemberCriteria createTimeGreaterThanOrEqualTo(Date value) {
        return new TemplateMemberCriteria().andCreateTimeGreaterThanOrEqualTo(value);
    }

    public static TemplateMemberCriteria createTimeLessThan(Date value) {
        return new TemplateMemberCriteria().andCreateTimeLessThan(value);
    }

    public static TemplateMemberCriteria createTimeLessThanOrEqualTo(Date value) {
        return new TemplateMemberCriteria().andCreateTimeLessThanOrEqualTo(value);
    }

    public static TemplateMemberCriteria createTimeIn(List<Date> values) {
        return new TemplateMemberCriteria().andCreateTimeIn(values);
    }

    public static TemplateMemberCriteria createTimeNotIn(List<Date> values) {
        return new TemplateMemberCriteria().andCreateTimeNotIn(values);
    }

    public static TemplateMemberCriteria createTimeBetween(Date value1, Date value2) {
        return new TemplateMemberCriteria().andCreateTimeBetween(value1, value2);
    }

    public static TemplateMemberCriteria createTimeNotBetween(Date value1, Date value2) {
        return new TemplateMemberCriteria().andCreateTimeNotBetween(value1, value2);
    }

    public static TemplateMemberCriteria updateTimeIsNull() {
        return new TemplateMemberCriteria().andUpdateTimeIsNull();
    }

    public static TemplateMemberCriteria updateTimeIsNotNull() {
        return new TemplateMemberCriteria().andUpdateTimeIsNotNull();
    }

    public static TemplateMemberCriteria updateTimeEqualTo(Date value) {
        return new TemplateMemberCriteria().andUpdateTimeEqualTo(value);
    }

    public static TemplateMemberCriteria updateTimeNotEqualTo(Date value) {
        return new TemplateMemberCriteria().andUpdateTimeNotEqualTo(value);
    }

    public static TemplateMemberCriteria updateTimeGreaterThan(Date value) {
        return new TemplateMemberCriteria().andUpdateTimeGreaterThan(value);
    }

    public static TemplateMemberCriteria updateTimeGreaterThanOrEqualTo(Date value) {
        return new TemplateMemberCriteria().andUpdateTimeGreaterThanOrEqualTo(value);
    }

    public static TemplateMemberCriteria updateTimeLessThan(Date value) {
        return new TemplateMemberCriteria().andUpdateTimeLessThan(value);
    }

    public static TemplateMemberCriteria updateTimeLessThanOrEqualTo(Date value) {
        return new TemplateMemberCriteria().andUpdateTimeLessThanOrEqualTo(value);
    }

    public static TemplateMemberCriteria updateTimeIn(List<Date> values) {
        return new TemplateMemberCriteria().andUpdateTimeIn(values);
    }

    public static TemplateMemberCriteria updateTimeNotIn(List<Date> values) {
        return new TemplateMemberCriteria().andUpdateTimeNotIn(values);
    }

    public static TemplateMemberCriteria updateTimeBetween(Date value1, Date value2) {
        return new TemplateMemberCriteria().andUpdateTimeBetween(value1, value2);
    }

    public static TemplateMemberCriteria updateTimeNotBetween(Date value1, Date value2) {
        return new TemplateMemberCriteria().andUpdateTimeNotBetween(value1, value2);
    }
}